"""Build our starting-zone routes from RestedXP's Forever guides, with the launch-day changes on top.

    python tools/fork_zones.py            (reads S:/forever-data/external/rxp; rerun after updating it)

Each zone is RestedXP's guide text plus a short list of edits. Every edit must match RestedXP's text
exactly once, so an upstream change that moves something fails loudly here instead of silently
producing a wrong route. Why each edit exists: S:/forever-data/research/leveling/findings.md.

Written files: Guides/<Zone>.lua, each shipping one guide through YR:ShipGuide.
"""
import os
import re

RXP = "S:/forever-data/external/rxp/Guides/Forever/"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RXP_GROUP = "RestedXP Forever Guide (A)"


def guide_block(file, name):
    src = open(RXP + file, encoding="utf-8").read()
    for b in re.findall(r"RXPGuides\.RegisterGuide\(\[\[(.*?)\]\]\)", src, re.S):
        if f"\n#name {name}\n" in b:
            return b
    raise SystemExit(f"{name} not found in {file}")


class Guide:
    def __init__(self, text):
        self.text = text

    def sub(self, old, new, why=""):
        n = self.text.count(old)
        assert n == 1, f"expected exactly one match upstream, found {n}: {old[:80]!r} ({why})"
        self.text = self.text.replace(old, new)

    def suball(self, old, new, count, why=""):
        n = self.text.count(old)
        assert n == count, f"expected {count} matches upstream, found {n}: {old[:80]!r} ({why})"
        self.text = self.text.replace(old, new)

    def before(self, anchor, new, why=""):
        """Insert new steps before the step that contains anchor."""
        i = self.text.index(anchor)
        i = self.text.rindex("\nstep", 0, i) + 1
        assert self.text.count(anchor) == 1, f"anchor not unique: {anchor[:60]!r}"
        self.text = self.text[:i] + new + self.text[i:]

    def header(self, name, nxt):
        """Our group and name; #next points back into RestedXP's own guides."""
        t = self.text
        t = re.sub(r"\n#group [^\n]*", "\n#group YippRoute Launch (A)", t, count=1)
        t = re.sub(r"\n#subgroup [^\n]*", "\n#subgroup Launch day", t, count=1)
        t = re.sub(r"\n#name [^\n]*", f"\n#name {name}", t, count=1)
        t = re.sub(r"\n#defaultfor [^\n]*", "", t, count=1)
        t = re.sub(r"\n#next [^\n]*", lambda _: "\n#next " + nxt, t, count=1)   # a function: nxt has backslashes
        self.text = t


def write(file, key, source, text, notes):
    head = (f"-- YippRoute: {notes}\n"
            f"-- GENERATED by tools/fork_zones.py from RestedXP's Forever guide ({source}, CC BY-NC-SA 4.0);\n"
            "-- only the edits listed in that script are ours. Do not edit by hand: change the script, rerun it.\n"
            "local _, YR = ...\n\n"
            f'YR:ShipGuide("{key}", [[')
    out = os.path.join(ROOT, "Guides", file)
    open(out, "w", encoding="utf-8", newline="\n").write(head + text + "]])\n")
    print(out, text.count("\nstep"), "steps")


# ---------------------------------------------------------------------------------------------------
# Northshire (Human), 1-6
# ---------------------------------------------------------------------------------------------------
def northshire():
    g = Guide(guide_block("Alliance-1-13_Human.lua", "1-6 Northshire"))
    g.header("1-6 Northshire (Launch)", "RestedXP Forever Guide (A)\\6-11 Elwynn Forest")

    # Wolf meat: every new Human starts on the Young Wolves round the Abbey. Timber Wolves drop the
    # meat too; their packs are on the south and east edges (Questie: 51,44 x6, 50,48 x3, 52,39 x3,
    # 52,36 x2), away from the crowd. Loop those first.
    g.sub('''    .goto 1429,49.052,38.270,0
    .goto 1429,45.708,38.720,0
    .goto 1429,47.976,39.422,0
    .waypoint 1429,49.052,38.270,45,0
    .waypoint 1429,48.362,37.582,45,0
    .waypoint 1429,47.136,37.636,45,0
    .waypoint 1429,46.870,36.906,45,0
    .waypoint 1429,46.476,37.034,45,0
    .waypoint 1429,46.465,38.272,45,0
    .waypoint 1429,45.896,38.013,45,0
    .waypoint 1429,45.708,38.720,45,0
    .waypoint 1429,46.302,39.994,45,0
    .waypoint 1429,45.718,40.733,45,0
    .waypoint 1429,46.399,41.838,45,0
    .waypoint 1429,46.741,40.987,45,0
    .waypoint 1429,47.703,40.299,45,0
    .waypoint 1429,47.976,39.422,45,0
    >>Kill |cRXP_ENEMY_Young Wolves|r and |cRXP_ENEMY_Timber Wolves|r. Loot them for their |cRXP_LOOT_Tough Wolf Meat|r''',
          '''    .goto 1429,50.8,44.2,0
    .goto 1429,50.3,47.6,0
    .goto 1429,52.2,39.2,0
    .waypoint 1429,50.8,44.2,45,0
    .waypoint 1429,50.3,47.6,45,0
    .waypoint 1429,48.5,46.8,45,0
    .waypoint 1429,50.8,44.2,45,0
    .waypoint 1429,52.2,39.2,45,0
    .waypoint 1429,52.1,36.2,45,0
    >>Kill |cRXP_ENEMY_Timber Wolves|r and |cRXP_ENEMY_Young Wolves|r on the south and east edges. Loot them for their |cRXP_LOOT_Tough Wolf Meat|r''', "frontier wolves")

    # Kobold Vermin: 22 of 31 are in the camp west of the Abbey where everyone goes; 9 are in the east
    # group (51,37). Start the loop there (RestedXP has this loop twice: the camp is visited twice).
    g.suball('''    #loop
    .goto 1429,47.601,36.720,0
    .goto 1429,49.215,37.010,0
    .goto 1429,47.569,34.967,0
    .goto 1429,47.601,36.720,45,0
    .goto 1429,47.381,36.314,45,0
    .goto 1429,47.611,35.863,45,0
    .goto 1429,48.314,36.487,45,0
    .goto 1429,49.070,36.438,45,0
    .goto 1429,49.215,37.010,45,0
    .goto 1429,49.838,36.413,45,0
    .goto 1429,50.105,35.668,45,0
    .goto 1429,49.823,35.161,45,0
    .goto 1429,48.845,35.066,45,0
    .goto 1429,47.569,34.967,45,0
    >>Kill |cRXP_ENEMY_Kobold Vermins|r. Loot them for the''',
          '''    #loop
    .goto 1429,51.0,37.2,0
    .goto 1429,49.8,35.2,0
    .goto 1429,47.6,36.7,0
    .goto 1429,51.0,37.2,45,0
    .goto 1429,50.105,35.668,45,0
    .goto 1429,49.823,35.161,45,0
    .goto 1429,48.845,35.066,45,0
    .goto 1429,47.569,34.967,45,0
    .goto 1429,47.611,35.863,45,0
    .goto 1429,47.601,36.720,45,0
    .goto 1429,48.314,36.487,45,0
    .goto 1429,49.215,37.010,45,0
    >>Kill |cRXP_ENEMY_Kobold Vermins|r, starting with the group east of the camp. Loot them for the''', 2, "frontier kobolds")

    # Garrick Padfoot is one spawn: at launch there's a queue for him.
    g.sub('''    >>Kill |cRXP_ENEMY_Garrick Padfoot|r. Loot him for his |cRXP_LOOT_Head|r''',
          '''    >>Kill |cRXP_ENEMY_Garrick Padfoot|r. Loot him for his |cRXP_LOOT_Head|r
    >>|cRXP_WARN_Group up with whoever is waiting|r''', "single-spawn boss")

    # Shinyfinder Narf (The Big Picture, new in Forever) is a single rare in Echo Ridge Mine.
    g.suball('''    >>Kill |cRXP_ENEMY_Shinyfinder Narf|r. Loot him for the |cRXP_LOOT_Sack of "Picture" Books|r''',
             '''    >>Kill |cRXP_ENEMY_Shinyfinder Narf|r. Loot him for the |cRXP_LOOT_Sack of "Picture" Books|r
    >>|cRXP_WARN_Group up with whoever is waiting|r''', 3, "single rare")
    return g


# ---------------------------------------------------------------------------------------------------
# Shadowglen (Night Elf), 1-6
# ---------------------------------------------------------------------------------------------------
def shadowglen():
    g = Guide(guide_block("Alliance-1-10_NightElf.lua", "1-6 Shadowglen"))
    g.header("1-6 Shadowglen (Launch)", "RestedXP Forever Guide (A)\\6-11 Teldrassil")

    # The Balance of Nature: every new Night Elf kills the Young Nightsabers and Thistle Boars round
    # Aldrassil. There are smaller groups on the east edge (Questie: 63,43 x6 sabers, 62,41 x3 and
    # 63,42 x3 boars); go there.
    g.suball('''    .goto 1438/1,657.75,10385.51,0,0''',
             '''    .goto 1438,62.9,42.9,0,0
    .goto 1438,62.2,41.0,0,0
    .goto 1438,61.2,45.0,0,0''', 2, "frontier sabers and boars")
    g.suball('''    >>Kill |cRXP_ENEMY_Young Nightsabers|r and |cRXP_ENEMY_Young Thistle Boars|r
    .goto 1438,62.9,42.9,0,0''',
             '''    >>Kill |cRXP_ENEMY_Young Nightsabers|r and |cRXP_ENEMY_Young Thistle Boars|r on the east edge, away from the crowd at the tree
    .goto 1438,62.9,42.9,0,0''', 2, "say where")

    # Githyiss the Vile is one spawn at the back of the cave.
    g.suball('''    >>Kill |cRXP_ENEMY_Githyiss the Vile|r loot it for it's |T134298:0|t[|cRXP_LOOT_Fang|r]''',
             '''    >>Kill |cRXP_ENEMY_Githyiss the Vile|r loot it for it's |T134298:0|t[|cRXP_LOOT_Fang|r]
    >>|cRXP_WARN_Group up with whoever is waiting|r''', 1, "single-spawn boss")
    return g


if __name__ == "__main__":
    n = northshire()
    write("Northshire.lua", "northshire", "Guides/Forever/Alliance-1-13_Human.lua", n.text,
          "launch-day Northshire Valley (Human, every class).")
    s = shadowglen()
    write("Shadowglen.lua", "shadowglen", "Guides/Forever/Alliance-1-10_NightElf.lua", s.text,
          "launch-day Shadowglen (Night Elf, every class).")
