"""Build Guides/DunMorogh.lua: RestedXP's "5-11 Dun Morogh" (Forever, Dwarf/Gnome) with our changes.

    python tools/fork_dunmorogh.py      (reads S:/forever-data/external/rxp; rerun after updating that clone)

Changes, each asserted so an upstream edit that moves them fails loudly instead of silently:
  * our group and name, #next pointing back into RestedXP's own guides;
  * Blacksmithing at Tognus and Tools for Steelgrill from Tharek before the campfire (the user's order);
  * Loslor also sells the Apprentice's Mining Pack and the Blacksmith Hammer we need.
"""
import os
import re

SRC = "S:/forever-data/external/rxp/Guides/Forever/Alliance-1-14_DwarfGnome.lua"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Guides", "DunMorogh.lua")
RXP_GROUP = "RestedXP Forever Guide (A)"

src = open(SRC, encoding="utf-8").read()
blocks = re.findall(r"RXPGuides\.RegisterGuide\(\[\[(.*?)\]\]\)", src, re.S)
guide = next(b for b in blocks if "\n#name 5-11 Dun Morogh\n" in b)


def sub(old, new):
    global guide
    assert guide.count(old) == 1, f"not exactly once upstream: {old[:70]!r}"
    guide = guide.replace(old, new)


sub("#version 1\n", "#version 1\n")
sub("#group RestedXP Forever Guide (A)\n", "#group YippRoute Launch (A)\n")
sub("#subgroup Speedrun Guide 1-20\n", "#subgroup Launch day\n")
sub("#name 5-11 Dun Morogh\n", "#name 5-11 Dun Morogh (Launch)\n")
sub("#defaultfor Dwarf/Gnome\n", "")
nxt = re.search(r"#next (.*)\n", guide).group(1)
sub(f"#next {nxt}\n", "#next " + ";".join(RXP_GROUP + "\\" + n for n in nxt.split(";")) + "\n")

# Blacksmithing and Tools for Steelgrill first, then the campfire: find the step with The Adventurer
FIRST = """step
    .goto 1426,45.344,51.936
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tognus Flintfire|r
    .train 2018 >> Train |T136241:0|t[Blacksmithing]
    .target Tognus Flintfire
step
    .goto 1426/0,-464.45,-5573.78
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Tharek Blackstone|r
    .accept 400 >> Accept Tools for Steelgrill
    .target Tharek Blackstone
"""
i = guide.index("    .turnin 96628 >>Turn in The Adventurer")
i = guide.rindex("\nstep\n", 0, i) + 1
guide = guide[:i] + FIRST + guide[i:]

sub("""    >>|cRXP_BUY_Buy a|r |T134708:0|t[Mining Pick]>>|cRXP_BUY_. If you can't afford it, skip this step|r
    .collect 2901,1 --Mining Pick (1)
""", """    >>|cRXP_BUY_Buy a|r |T134708:0|t[Mining Pick]|cRXP_BUY_, an|r |T133635:0|t[Apprentice's Mining Pack] |cRXP_BUY_and a|r |T133057:0|t[Blacksmith Hammer]
    .collect 2901,1 --Mining Pick (1)
    .collect 277115,1 --Apprentice's Mining Pack (1)
    .collect 5956,1 --Blacksmith Hammer (1)
""")

HEAD = """-- YippRoute: Dun Morogh 5-11 after our Coldridge opener. GENERATED by tools/fork_dunmorogh.py from
-- RestedXP's Forever guide (Guides/Forever/Alliance-1-14_DwarfGnome.lua, CC BY-NC-SA 4.0); only the
-- changes listed in that script are ours. Do not edit by hand: change the script and rerun it.
local _, YR = ...

YR:ShipGuide("dunmorogh", [["""
open(OUT, "w", encoding="utf-8", newline="\n").write(HEAD + guide + "]])\n")
print(OUT, guide.count("\nstep"), "steps")
