"""Build our levelling routes after the starting zones from RestedXP's guides, as they are plus our changes.

    python tools/fork_rxp.py        (reads S:/forever-data/external/rxp; rerun after updating that clone)

Every guide in SOURCES becomes Guides/Levelling/<slug>.lua shipping one route (YR:ShipGuide) in our group:
  * cleaned of what never shows on WoW: Forever (tools/clean_guide.py);
  * quest pick-ups a duo or trio should split marked (tools/share_split.py);
  * its #next pointing at our copy where we ship one, else back into RestedXP's own group;
  * the per-route changes in EDITS (each must match RestedXP's text exactly, or the build fails).
Also writes Guides/Levelling/files.txt, the list the .toc needs (check_toc below keeps them in step).
"""
import os
import re
import sys

from clean_guide import clean
from share_split import mark

RXP = "S:/forever-data/external/rxp/Guides/"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Guides", "Levelling")
GROUP = "Headstart Launch (A)"

# (file under RXP, RestedXP's group for #next entries without one, [guide names])
SOURCES = [
    ("Forever/Alliance-1-13_Human.lua", "RestedXP Forever Guide (A)", ["6-11 Elwynn Forest", "11-13 Loch Modan"]),
    ("Forever/Alliance-1-14_DwarfGnome.lua", "RestedXP Forever Guide (A)",
     ["11-12 Elwynn (Dwarf/Gnome)", "12-14 Loch Modan (Dwarf/Gnome)", "11-13 Loch Modan (Hunter)"]),
    ("Forever/Alliance-1-10_NightElf.lua", "RestedXP Forever Guide (A)", ["6-11 Teldrassil"]),
    ("Forever/Alliance-11-20.lua", "RestedXP Forever Guide (A)",
     ["13-15 Westfall", "14-16 Darkshore", "16-19 Darkshore", "19-20 Redridge", "19-21 Darkshore/Ashenvale",
      "20-21 Darkshore/Ashenvale"]),
]

# Our changes per route: name -> [(old, new, why)]
EDITS = {}


def slug(name):
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def block(file, name):
    src = open(RXP + file, encoding="utf-8").read()
    for b in re.findall(r"RXPGuides\.RegisterGuide\(\[\[(.*?)\]\]\)", src, re.S):
        if f"\n#name {name}\n" in b:
            return b
    raise SystemExit(f"{name} not found in {file}")


def next_line(line, home, ours):
    """#next entries: ours stay plain (same group), RestedXP's get their group in front."""
    body, sep, cond = line.partition(" << ")
    out = []
    for entry in body.split(";"):
        entry = entry.strip()
        if "\\" in entry:
            out.append(entry)
        elif entry in ours:
            out.append(entry)
        else:
            out.append(home + "\\" + entry)
    return ";".join(out) + (sep + cond if sep else "")


def build(file, home, name, ours):
    text = block(file, name)
    text = re.sub(r"\n#group [^\n]*", "\n#group " + GROUP, text, count=1)
    text = re.sub(r"\n#subgroup [^\n]*", "\n#subgroup Levelling", text, count=1)
    text = re.sub(r"\n#defaultfor [^\n]*", "", text)
    text = re.sub(r"\n#next ([^\n]*)", lambda m: "\n#next " + next_line(m.group(1), home, ours), text)
    for old, new, why in EDITS.get(name, []):
        n = text.count(old)
        assert n == 1, f"{name}: expected one match upstream, found {n}: {old[:70]!r} ({why})"
        text = text.replace(old, new)
    text = clean(text)
    text, shared = mark(text)
    return text, shared


def main():
    os.makedirs(OUT, exist_ok=True)
    ours = {n for _, _, names in SOURCES for n in names}
    files = []
    for file, home, names in SOURCES:
        for name in names:
            text, shared = build(file, home, name, ours)
            key = slug(name)
            path = os.path.join(OUT, key + ".lua")
            head = (f"-- Headstart: {name}. GENERATED by tools/fork_rxp.py from RestedXP's guide ({file},\n"
                    "-- CC BY-NC-SA 4.0); only the changes in that script are ours. Do not edit by hand.\n"
                    "local _, YR = ...\n\n"
                    f'YR:ShipGuide("{key}", [[')
            open(path, "w", encoding="utf-8", newline="\n").write(head + text + "]])\n")
            files.append("Guides\\Levelling\\" + key + ".lua")
            print(f"{name:32s} {text.count(chr(10) + 'step'):4d} steps" + (f"   {'; '.join(shared)}" if shared else ""))
    open(os.path.join(OUT, "files.txt"), "w", encoding="utf-8", newline="\n").write("\n".join(files) + "\n")
    check_toc(files)


def check_toc(files):
    """The .toc must load every generated route, after the starting zones."""
    toc = open(os.path.join(ROOT, "Headstart.toc"), encoding="utf-8").read()
    missing = [f for f in files if f not in toc]
    if missing:
        print("add to Headstart.toc:\n" + "\n".join(missing))
        sys.exit(1)


if __name__ == "__main__":
    main()
