"""Generate Data/TrainerSpells.lua (for Reminders.lua): every rank a class trainer teaches, by level.

    python tools/gen_trainer_spells.py [schema]      (default: the newest wow_classic_beta build)

From the game's tables: skilllineability rows with AcquireMethod 0 on a class's own skill lines,
their level from spelllevels and their rank from spell.NameSubtext. Talent spells (talent.SpellRank
and traitdefinition.SpellID) are left out as first ranks: the trainer only teaches their later ranks,
and only once you have the one before, which the addon checks with IsPlayerSpell.
    YR.TrainerSpells[CLASS] = { { spellID, level, "name", rank or 0, raceMask or 0, talent 0/1 }, ... }  by level
"""
import os
import re
import sys

import duckdb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = r"S:\forever-data\db\forever.duckdb"
OUT = os.path.join(ROOT, "Data", "TrainerSpells.lua")
CLASSES = {1: "WARRIOR", 2: "PALADIN", 3: "HUNTER", 4: "ROGUE", 5: "PRIEST", 7: "SHAMAN", 8: "MAGE", 9: "WARLOCK", 11: "DRUID"}


def main():
    c = duckdb.connect(DB, read_only=True)
    s = sys.argv[1] if len(sys.argv) > 1 else c.sql(
        "select schema_name from main.builds where schema_name like 'wow_classic_beta_%' order by schema_name desc limit 1").fetchone()[0]
    line_class = {}
    for sid, mask in c.sql(f"""select sl.ID, cast(i.ClassMask as bigint) from {s}.skillline sl
            join {s}.skillraceclassinfo i on i.SkillID = sl.ID where sl.CategoryID = '7'""").fetchall():
        for cid, token in CLASSES.items():
            if mask == 1 << (cid - 1):
                line_class[sid] = token
    talent = set()
    for k in range(9):
        talent |= {r[0] for r in c.sql(f'select cast("SpellRank[{k}]" as int) from {s}.talent').fetchall() if r[0]}
    talent |= {r[0] for r in c.sql(f"select cast(SpellID as int) from {s}.traitdefinition").fetchall() if r[0]}
    rows = c.sql(f"""
        select distinct a.SkillLine, cast(a.Spell as int), n.Name_lang, sp.NameSubtext_lang,
            min(cast(l.SpellLevel as int)), cast(a."RaceMasks[0]" as bigint)
        from {s}.skilllineability a
        join {s}.spellname n on n.ID = a.Spell
        left join {s}.spell sp on sp.ID = a.Spell
        join {s}.spelllevels l on l.SpellID = a.Spell
        where a.AcquireMethod = '0' and cast(l.SpellLevel as int) > 0
        group by 1, 2, 3, 4, 6""").fetchall()
    out, talent_names = {}, {}
    for line, spell, name, sub, level, race in rows:
        token = line_class.get(line)
        if not token:
            continue
        m = re.match(r"Rank (\d+)", sub or "")
        rank = int(m.group(1)) if m else 0
        if spell in talent and rank <= 1:
            talent_names.setdefault(token, set()).add(name)
            continue
        # One spell can have a row per race group: OR their masks, and any "every race" row wins.
        prev = out.setdefault(token, {}).get(spell)
        race = race or 0
        if prev:
            race = 0 if (prev[3] == 0 or race == 0) else (prev[3] | race)
            level = min(level, prev[0])
        out[token][spell] = (level, name, rank, race)

    def q(t):
        return '"' + t.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [f"-- GENERATED by tools/gen_trainer_spells.py from {s}. Do not edit; regenerate.",
             "-- [class] = { { spellID, level, name, rank (0 = none), raceMask (0 = every race), talent (1: rank 1 is a talent) }, ... }",
             "local _, YR = ...", "YR.TrainerSpells = {"]
    n = 0
    for token in sorted(out):
        lines.append(f"    {token} = {{")
        for spell, (level, name, rank, race) in sorted(out[token].items(), key=lambda kv: (kv[1][0], kv[1][1], kv[1][2])):
            t = 1 if name in talent_names.get(token, ()) else 0
            lines.append(f"        {{ {spell}, {level}, {q(name)}, {rank}, {race}, {t} }},")
            n += 1
        lines.append("    },")
    lines += ["}", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"{n} trainer ranks for {len(out)} classes from {s}")


if __name__ == "__main__":
    main()
