"""Generate Data/Restock.lua (for Restock.lua): the vendor reagents each class's spells use.

    python tools/gen_restock.py [schema]      (default: the newest wow_classic_beta build)

Read from the game's own tables (skilllineability -> spellreagents -> itemsparse), so it is what
Forever's spells actually take, not a vanilla list from memory. Items with no buy price (Soul Shard)
are left out: no vendor sells them.
    YR.RestockData[CLASS] = { { item, default count, { { spellID, level, name }, ... } }, ... }
"""
import os
import sys

import duckdb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = r"S:\forever-data\db\forever.duckdb"
OUT = os.path.join(ROOT, "Data", "Restock.lua")
CLASSES = {1: "WARRIOR", 2: "PALADIN", 3: "HUNTER", 4: "ROGUE", 5: "PRIEST", 7: "SHAMAN", 8: "MAGE", 9: "WARLOCK", 11: "DRUID"}
# How many to keep by default. Anything not named starts at 0 (off) until the player sets it.
DEFAULTS = {
    17031: 5, 17032: 5, 17020: 20, 17056: 10,       # mage: teleport and portal runes, powder, feathers
    17033: 2, 21177: 40,                            # paladin: Divine Intervention, greater blessings
    17028: 20, 17029: 20,                           # priest: candles
    5140: 10,                                       # rogue: Flash Powder (Blinding Powder is crafted)
    17030: 3, 17057: 5, 17058: 5,                   # shaman: ankhs, scales, oil
    5565: 2, 16583: 1,                              # warlock
    17021: 20, 17026: 20,                           # druid: Gift of the Wild
    17034: 3, 17035: 3, 17036: 3, 17037: 3, 17038: 3,   # druid: Rebirth (only the top rank's seed is bought)
}


def main():
    c = duckdb.connect(DB, read_only=True)
    s = sys.argv[1] if len(sys.argv) > 1 else c.sql(
        "select schema_name from main.builds where schema_name like 'wow_classic_beta_%' order by schema_name desc limit 1").fetchone()[0]
    line_class = {}
    for sid, mask in c.sql(f"""select sl.ID, cast(i.ClassMask as bigint) from {s}.skillline sl
            join {s}.skillraceclassinfo i on i.SkillID = sl.ID where sl.CategoryID = '7'""").fetchall():
        for cid, token in CLASSES.items():
            if mask == 1 << (cid - 1):
                line_class[sid] = token
    reagents = " union all ".join(f'select SpellID, "Reagent[{k}]" r from {s}.spellreagents' for k in range(8))
    rows = c.sql(f"""
        select a.SkillLine, cast(a.Spell as int), n.Name_lang, cast(x.r as int), min(cast(l.SpellLevel as int))
        from {s}.skilllineability a
        join ({reagents}) x on x.SpellID = a.Spell
        join {s}.spellname n on n.ID = a.Spell
        join {s}.itemsparse it on it.ID = cast(x.r as int)
        left join {s}.spelllevels l on l.SpellID = a.Spell
        where cast(x.r as int) > 0 and cast(it.BuyPrice as int) > 0 and a.AcquireMethod in ('0', '2')
        group by 1, 2, 3, 4""").fetchall()
    out = {}
    for line, spell, name, item, level in rows:
        token = line_class.get(line)
        if token:
            out.setdefault(token, {}).setdefault(item, set()).add((spell, level or 0, name))

    def q(t):
        return '"' + t.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [f"-- GENERATED by tools/gen_restock.py from {s}. Do not edit; regenerate.",
             "-- [class] = { { item, default count, { { spellID, level, spell name }, ... } }, ... }",
             "local _, YR = ...", "YR.RestockData = {"]
    n = 0
    for token in sorted(out):
        lines.append(f"    {token} = {{")
        for item in sorted(out[token]):
            spells = ", ".join(f"{{ {sp}, {lv}, {q(nm)} }}" for sp, lv, nm in sorted(out[token][item]))
            lines.append(f"        {{ {item}, {DEFAULTS.get(item, 0)}, {{ {spells} }} }},")
            n += 1
        lines.append("    },")
    lines += ["}", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"{n} reagents for {len(out)} classes from {s}")


if __name__ == "__main__":
    main()
