"""Generate Data/QuestIDs.lua: the quest IDs /yroute scan asks the server about, most useful first.

    python tools/gen_quest_ids.py

  1. route: every quest in RXP's Alliance Forever guides (S:/forever-data/external/rxp)
  2. new:   quest IDs in the newest beta client's questv2 but not in Classic Era's
  3. rest:  every other ID in the beta questv2 or in QuestieDB (questv2 is sparse: quest 308 is in
            RXP's route but not in it, so QuestieDB's list is added rather than trusted to overlap)
"""
import glob
import json
import os
import re

import duckdb

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Data", "QuestIDs.lua")
DB = "S:/forever-data/db/forever.duckdb"
QUESTIE = "S:/forever-data/research/leveling/data/Quest.json"
RXP = "S:/forever-data/external/rxp/Guides/Forever/"

c = duckdb.connect(DB, read_only=True)
beta = c.sql("select schema_name from main.builds where schema_name like 'wow_classic_beta_%' order by schema_name desc limit 1").fetchone()[0]
era = c.sql("select schema_name from main.builds where schema_name like 'wow_classic_era_%' order by schema_name desc limit 1").fetchone()[0]
ids = lambda s: {int(r[0]) for r in c.sql(f"select ID from {s}.questv2").fetchall()}
beta_ids, era_ids = ids(beta), ids(era)
questie = {int(k) for k in json.load(open(QUESTIE))}

route = []
for f in sorted(glob.glob(RXP + "Alliance-*.lua") + glob.glob(RXP + "RestedXP-Skyborne.lua")):
    for m in re.finditer(r"\.(?:accept|turnin|complete) -?(\d+)", open(f, encoding="utf-8").read()):
        q = int(m.group(1))
        if q not in route:
            route.append(q)
seen = set(route)
new = sorted(beta_ids - era_ids - seen)
seen |= set(new)
rest = sorted((beta_ids | questie) - seen)


def block(name, xs):
    lines, row = [], []
    for x in xs:
        row.append(str(x))
        if len(row) == 16:
            lines.append("        " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("        " + ", ".join(row) + ",")
    return [f"    {name} = {{"] + lines + ["    },"]


out = [f"-- GENERATED by tools/gen_quest_ids.py ({beta} vs {era}). Do not edit; regenerate.",
       "local _, YR = ...", "YR.QUEST_IDS = {"]
out += block("route", route) + block("new", new) + block("rest", rest) + ["}"]
with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write("\n".join(out) + "\n")
print(f"{OUT}: route {len(route)}, new {len(new)}, rest {len(rest)}")
