"""Generate Data/SpellLevels.lua: for every class, each trainable spell NAME -> the level its first rank is learned.

    python tools/gen_spell_levels.py [schema]      (default: the newest wow_classic_beta schema)

Source: S:/forever-data/db/forever.duckdb (client DB2).
  * class spell lines = skillline CategoryID 7, mapped to a class through skillraceclassinfo.ClassMask;
  * only AcquireMethod 0 (trained) and 2 (auto-learned). AcquireMethod 3 rows are Season of Discovery
    rune variants whose SpellLevel is 1 (Flash of Light 412020, Avenging Wrath 407788 ...) and would
    make a level-20 spell look like a level-1 one;
  * level = min(spelllevels.SpellLevel) over the ranks; rows without a level (talents) are dropped.
Names are enUS, which is what the macros /cast by.
"""
import os
import sys
import duckdb

DB = "S:/forever-data/db/forever.duckdb"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Data", "SpellLevels.lua")
NOT_CLASS_SPELLS = {"Engraving", "Runes", "Meditation", "Explorer Imp", "Mounts", "Companions", "Beast Training"}
CLASSES = {1: "WARRIOR", 2: "PALADIN", 3: "HUNTER", 4: "ROGUE", 5: "PRIEST", 7: "SHAMAN", 8: "MAGE", 9: "WARLOCK", 11: "DRUID"}

c = duckdb.connect(DB, read_only=True)
schema = sys.argv[1] if len(sys.argv) > 1 else c.sql(
    "select schema_name from main.builds where schema_name like 'wow_classic_beta_%' order by schema_name desc limit 1").fetchone()[0]

lines = c.sql(f"""
    select sl.ID, sl.DisplayName_lang, cast(i.ClassMask as bigint)
    from {schema}.skillline sl join {schema}.skillraceclassinfo i on i.SkillID = sl.ID
    where sl.CategoryID = '7'""").fetchall()
line_class = {}
for sid, name, mask in lines:
    if name in NOT_CLASS_SPELLS or mask is None or mask <= 0:
        continue
    for cid, token in CLASSES.items():
        if mask == 1 << (cid - 1):
            line_class[sid] = token

rows = c.sql(f"""
    select a.SkillLine, n.Name_lang, min(cast(l.SpellLevel as int))
    from {schema}.skilllineability a
    join {schema}.spellname n on n.ID = a.Spell
    join {schema}.spelllevels l on l.SpellID = a.Spell
    where a.AcquireMethod in ('0', '2') and cast(l.SpellLevel as int) > 0
    group by 1, 2""").fetchall()

levels = {}
for sid, name, lvl in rows:
    token = line_class.get(sid)
    if token:
        cur = levels.setdefault(token, {}).get(name)
        levels[token][name] = lvl if cur is None else min(cur, lvl)


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


out = ["-- GENERATED by tools/gen_spell_levels.py from " + schema + ". Do not edit; regenerate.",
       "-- [class token] = { [spell name] = level its first rank is learned }",
       "local _, YR = ...", "YR.Setup = YR.Setup or {}", "local YS = YR.Setup", "YS.SPELL_LEVELS = {"]
for token in sorted(levels):
    out.append(f"    {token} = {{")
    for name, lvl in sorted(levels[token].items(), key=lambda kv: (kv[1], kv[0])):
        out.append(f"        [{lua_str(name)}] = {lvl},")
    out.append("    },")
out.append("}")

# Racials (Stoneform, Escape Artist, ...): the auto-learned spells of the racial skill lines, category 9.
racials = sorted(r[0] for r in c.sql(f"""
    select distinct n.Name_lang
    from {schema}.skilllineability a
    join {schema}.skillline sl on sl.ID = a.SkillLine
    join {schema}.spellname n on n.ID = a.Spell
    where sl.CategoryID = '9' and a.AcquireMethod = '2'
      and sl.DisplayName_lang like '%Racial%'""").fetchall())   # category 9 also holds Fishing, Cooking, Riding ...
out.append("-- racial spells: kept whatever the level limit, since every character has them from level 1")
out.append("YS.RACIALS = {")
out += [f"    [{lua_str(n)}] = true," for n in racials]
out.append("}")

# Profession spells (Find Minerals, Smelting, Blacksmithing, Basic Campfire, recipes ...): every spell of the
# primary profession lines (category 11) and of First Aid, Cooking, Fishing and Survival. They go back on the
# bars only once the new character has learned them.
SECONDARY = "('129', '185', '356', '142')"
# One name can be several spells: the ranks (Apprentice/Journeyman Blacksmithing) and Forever's hidden
# same-named spells (a purple-gem "Blacksmithing" every blacksmith knows). All IDs are kept, lowest first,
# and Set up layout picks the known one with the main's icon.
prof_ids = {}
for name, sid in c.sql(f"""
    select distinct n.Name_lang, cast(a.Spell as int)
    from {schema}.skilllineability a
    join {schema}.skillline sl on sl.ID = a.SkillLine
    join {schema}.spellname n on n.ID = a.Spell
    where (sl.CategoryID = '11' or sl.ID in {SECONDARY} or sl.ParentSkillLineID in {SECONDARY})
      and sl.DisplayName_lang not like '%DNT%'""").fetchall():
    prof_ids.setdefault(name, []).append(sid)
profs = sorted(prof_ids)
out.append("-- profession spells: [name] = { spell IDs with that name }; placed once the character has learned one")
out.append("YS.PROFESSIONS = {")
out += [f"    [{lua_str(n)}] = {{ {', '.join(str(i) for i in sorted(prof_ids[n]))} }}," for n in profs]
out.append("}")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print(f"{OUT}: {sum(len(v) for v in levels.values())} spells over {len(levels)} classes, {len(racials)} racials, {len(profs)} profession spells, from {schema}")
