"""Generate Data/Crafting.lua (for Bank.lua) from Guildhall's generated recipe data.

    python tools/gen_crafting.py

Guildhall/Data/Recipes.lua is itself GENERATED from the game's tables by
forever-data/tools/gen_addon_data.py; rerun this after that one, so both carry the same build.
Two lookups come out of it:
    RECIPE_ITEMS[recipeItemID] = { professionLine, skillToLearn, recipeSpellID }
    REAGENTS[itemID] = { professionLine, ... }    every profession with a recipe that uses it
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Guildhall", "Data", "Recipes.lua")
OUT = os.path.join(ROOT, "Data", "Crafting.lua")


def main():
    text = open(SRC, encoding="utf-8").read()
    build = re.search(r'GH\.Data\.build = "([^"]+)"', text).group(1)
    profs = re.search(r"GH\.Data\.professions = \{(.*?)\n\}", text, re.S).group(1)
    lines = sorted(int(x) for x in re.findall(r"\[(\d+)\] =", profs))
    body = re.search(r"GH\.Data\.recipes = \{(.*?)\n\}", text, re.S).group(1)
    recipe_items, reagents = {}, {}
    for spell, row in re.findall(r'\[(\d+)\] = "([^"]*)"', body):
        f = row.split("|")
        prof, learn = int(f[0]), int(f[1] or 0)
        for part in filter(None, f[6].split(",")):
            reagents.setdefault(int(part.split("*")[0]), set()).add(prof)
        for item in filter(None, f[8].split(",")):
            item = int(item)
            # Two spells taught by one item never happens in the data; if it ever does, the lower
            # skill wins, which is the one that decides whether you can learn it now.
            old = recipe_items.get(item)
            if not old or learn < old[1]:
                recipe_items[item] = (prof, learn, int(spell))
    out = [
        "-- Headstart - what crafts with what, for the bank (Bank.lua). GENERATED by tools/gen_crafting.py",
        f"-- from Guildhall/Data/Recipes.lua (build {build}) - do not edit.",
        "local ADDON, YR = ...",
        "YR.Crafting = {",
        f'    build = "{build}",',
        "    professions = { " + ", ".join(str(x) for x in lines) + " },",
        "    -- [recipeItemID] = { professionLine, skillToLearn, recipeSpellID }",
        "    recipeItems = {",
    ]
    for item in sorted(recipe_items):
        p, l, s = recipe_items[item]
        out.append(f"        [{item}] = {{ {p}, {l}, {s} }},")
    out += ["    },", "    -- [itemID] = { professionLine, ... }: every profession with a recipe that uses it", "    reagents = {"]
    for item in sorted(reagents):
        out.append(f"        [{item}] = {{ " + ", ".join(str(p) for p in sorted(reagents[item])) + " },")
    out += ["    },", "}", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(recipe_items)} recipe items, {len(reagents)} reagents, build {build}")


if __name__ == "__main__":
    main()
