"""Generate Data/Consumables.lua (for CraftRemind.lua): the stones, oils and bandages you can make.

    python tools/gen_consumables.py [schema]      (default: the newest wow_classic_beta build)

The recipes come from Guildhall/Data/Recipes.lua (generated from the game's tables), what they make
is sorted by the game's item class: 0/8 item enhancements named Sharpening Stone, Weightstone or
Wizard/Mana Oil, and 0/7 bandages.
    YR.Consumables = { { recipeSpellID, professionLine, rank (its yellow skill: higher = better), createdItem, qty, kind,
                         { reagentItem, count, reagentItem, count, ... } }, ... }
"""
import os
import re
import sys

import duckdb

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "..", "Guildhall", "Data", "Recipes.lua")
DB = r"S:\forever-data\db\forever.duckdb"
OUT = os.path.join(ROOT, "Data", "Consumables.lua")


def kind_of(cls, sub, name):
    if cls == 0 and sub == 7:
        return "bandage"
    if cls == 0 and sub == 8:
        if "Sharpening Stone" in name:
            return "sharpening"
        if "Weightstone" in name:
            return "weightstone"
        if re.search(r"(Wizard|Mana) Oil", name):
            return "oil"
    return None


def main():
    c = duckdb.connect(DB, read_only=True)
    s = sys.argv[1] if len(sys.argv) > 1 else c.sql(
        "select schema_name from main.builds where schema_name like 'wow_classic_beta_%' order by schema_name desc limit 1").fetchone()[0]
    items = {int(i): (int(cl), int(sc), n) for i, cl, sc, n in c.sql(
        f"select i.ID, i.ClassID, i.SubclassID, x.Display_lang from {s}.item i join {s}.itemsparse x on x.ID = i.ID").fetchall()}
    text = open(SRC, encoding="utf-8").read()
    build = re.search(r'GH\.Data\.build = "([^"]+)"', text).group(1)
    body = re.search(r"GH\.Data\.recipes = \{(.*?)\n\}", text, re.S).group(1)
    rows = []
    for spell, row in re.findall(r'\[(\d+)\] = "([^"]*)"', body):
        f = row.split("|")
        if "e" in f[9]:
            continue                                   # an enchant: "createdItem" is an enchant ID
        created = int(f[4] or 0)
        info = items.get(created)
        kind = info and kind_of(*info)
        if not kind:
            continue
        reagents = []
        for part in filter(None, f[6].split(",")):
            item, count = part.split("*")
            reagents += [int(item), int(count)]
        rows.append((int(spell), int(f[0]), int(f[2] or f[1] or 0), created, int(f[5] or 1), kind, reagents, info[2]))
    rows.sort(key=lambda r: (r[5], r[2], r[0]))
    out = [f"-- GENERATED by tools/gen_consumables.py from Guildhall/Data/Recipes.lua (build {build}) and {s}.",
           "-- Do not edit; regenerate.",
           "-- { recipeSpellID, professionLine, rank (yellow skill: higher is the better item), createdItem, qty, kind, { reagent, count, ... } }",
           "local _, YR = ...", "YR.Consumables = {"]
    for spell, prof, learn, created, qty, kind, reagents, name in rows:
        out.append(f'    {{ {spell}, {prof}, {learn}, {created}, {qty}, "{kind}", {{ {", ".join(map(str, reagents))} }} }},   -- {name}')
    out += ["}", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out))
    print(f"{len(rows)} recipes: " + ", ".join(f"{k} {sum(1 for r in rows if r[5] == k)}" for k in
                                               ("sharpening", "weightstone", "oil", "bandage")))


if __name__ == "__main__":
    main()
