-- Headstart: 21-23 Ashenvale. GENERATED by tools/fork_rxp.py from RestedXP's guide (RestedXP Alliance 11-23.lua,
-- CC BY-NC-SA 4.0); only the changes in that script are ours. Do not edit by hand.
local _, YR = ...

YR:ShipGuide("21_23_ashenvale", [[
#forever
<< Alliance
#name 21-23 Ashenvale
#version 1
#group Headstart Launch (A)
#groupid RXP-SRGCE-A1
#next 23-24 Wetlands;24-27 Redridge/Duskwood
step
    #role A,B,C
    >>Blackfathom Deeps quests in Darnassus first, for the group run at the Zoram Strand
    .fly Auberdine >> Fly to Auberdine
    .isNotOnQuest 1198
step
    #role A,B,C
    .goto 1439,33.2,39.9
    .zone Teldrassil >> Take the boat to Teldrassil
    .isNotOnQuest 1198
step
    #role A,B,C
    .goto 1438,58.399,94.016
    .fp Rut'theran >> Get the Rut'theran Village flight path
    .isNotOnQuest 1198
step
    #role A,B,C
    .goto 1438/1,968.90,8795.34
    .zone Darnassus >> Take the purple portal into Darnassus
    .isNotOnQuest 1198
step
    #role A,B,C
    .goto 1457,55.36,25.03
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dawnwatcher Shaedlass|r
    .target Dawnwatcher Shaedlass
    .accept 1198 >> Accept In Search of Thaelrid
step
    #role A,B,C
    .goto 1457,55.24,23.99
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Argent Guard Manados|r
    .target Argent Guard Manados
    .accept 1199 >> Accept Twilight Falls
step
    #role A,B,C
    .goto 1457,31.0,41.5
    .zone Teldrassil >> Take the purple portal back to Rut'theran Village
    .zoneskip Ashenvale
step
    #role A,B,C
    .goto 1438,58.399,94.016
    .fly Astranaar >> Fly to Astranaar
    .zoneskip Ashenvale
step
#xprate <1.5 << !Druid
    .goto 1440,26.2,38.6
.target Delgren the Purifier
>>Talk to |cRXP_FRIENDLY_Delgren the Purifier|r
    .turnin 967 >> Turn in The Tower of Althalaxx
    .isOnQuest 967
step
#xprate <1.5
    .isQuestTurnedIn 967
    .goto 1440,26.2,38.6
.target Delgren the Purifier
>>Talk to |cRXP_FRIENDLY_Delgren the Purifier|r
    .accept 970 >> Accept The Tower of Althalaxx
    .maxlevel 21
step
    .goto 1440,26.4,38.6
.target Orendil Broadleaf
>>Talk to |cRXP_FRIENDLY_Orendil Broadleaf|r
    .accept 1010 >> Accept Bathran's Hair
step
    .goto 1440,31.3,23.2
	>> Loot the brown sacks in the area, they can be hard to spot.
    .complete 1010,1 --Collect Bathran's Hair (x5)
step
#xprate <1.5
    .isOnQuest 970
    .goto 1440,31.4,31.0
	>> The drop rate is very very low, just keep killing mobs.
    .complete 970,1 --Collect Glowing Soul Gem (x1)
    .maxlevel 21
step
    .goto 1440,26.4,38.6
>>Talk to |cRXP_FRIENDLY_Orendil Broadleaf|r
    .turnin 1010 >> Turn in Bathran's Hair
.target Orendil Broadleaf
    .accept 1020 >> Accept Orendil's Cure
step
#xprate <1.5
    .isQuestComplete 970
    .goto 1440,26.2,38.6
.target Delgren the Purifier
>>Talk to |cRXP_FRIENDLY_Delgren the Purifier|r
    .turnin 970 >> Turn in The Tower of Althalaxx
step
    #xprate <1.5
    .isQuestTurnedIn 970
    .goto 1440,26.2,38.6
.target Delgren the Purifier
>>Talk to |cRXP_FRIENDLY_Delgren the Purifier|r
    .accept 973 >> Accept The Tower of Althalaxx
step
    .goto 1440,34.40,48.00
    .fp Astranaar>> Get the Astranaar Flight Path
step
    .goto 1440,34.7,48.8
.target Shindrell Swiftfire
>>Talk to |cRXP_FRIENDLY_Shindrell Swiftfire|r
    .accept 1008 >> Accept The Zoram Strand
step
    .goto 1440,36.618,49.581
.target Raene Wolfrunner
>>Talk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .accept 1054 >> Accept Culling the Threat
step
#xprate <1.7
    .goto 1440,36.618,49.581
.target Raene Wolfrunner
>>Talk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .accept 991 >> Accept Raene's Cleansing
step
    #timer Orendil's Cure roleplay
    .goto 1440,37.3,51.8
    >> Wait for the roleplay, it takes 26 seconds.
>>Talk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .turnin 1020 >> Turn in Orendil's Cure
    .timer 26,Orendil's Cure roleplay
.target Pelturas Whitemoon
    .accept 1033 >> Accept Elune's Tear
step
    .goto 1440,46.2,45.9
	>> Click on the small blue seed on the ground.
    .complete 1033,1 --Collect Elune's Tear (x1)
step
    .goto 1440,37.8,34.7
	>> Kill Dal Bloodclaw and loot him for his skull. He patrols around the camps.
	.unitscan Dal Bloodclaw
    .complete 1054,1 --Collect Dal Bloodclaw's Skull (x1)
step
    .goto 1440,36.618,49.581
.target Raene Wolfrunner
>>Talk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .turnin 1054 >> Turn in Culling the Threat
step
    .goto 1440,37.3,51.8
    >> Wait for the roleplay, it takes 10 seconds
>>Talk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .turnin 1033 >> Turn in Elune's Tear
    .timer 10,Elune's tear roleplay
.target Pelturas Whitemoon
    .accept 1034 >> Accept The Ruins of Stardust
step
    .goto 1440,33.3,67.4
	>> Loot the stardust in the area
    .complete 1034,1 --Collect Handful of Stardust (x5)
step
#xprate <1.5
    .isOnQuest 973
    .goto 1440,25.3,60.8
	>> Kill Ilkrud and loot him for his tome, you can stun him to stop him from summoning help.
    .complete 973,1 --Collect Ilkrud Magthrull's Tome (x1)
step
    .goto 1440,22.7,51.9
    >> Run up and over the mountains then turn in Therylune's Escape
.target Therysil
>>Talk to |cRXP_FRIENDLY_Therysil|r
    .turnin 945 >> Turn in Therylune's Escape
    .isQuestComplete 945
step
    .goto 1440,22.7,51.9
    .abandon 945 >> Abandon Therylune's Escape if you haven't completed it
step
#xprate <1.5
    .isOnQuest 973
    .goto 1440,26.196,38.698
.target Delgren the Purifier
>>Talk to |cRXP_FRIENDLY_Delgren the Purifier|r
    .turnin 973 >> Turn in The Tower of Althalaxx
step
#xprate <1.7
    .goto 1440,20.3,42.4
>>Talk to |cRXP_FRIENDLY_Teronis' Corpse|r
    .turnin 991 >> Turn in Raene's Cleansing
.target Teronis' Corpse
    .accept 1023 >> Accept Raene's Cleansing
step
#xprate <1.7
    .goto 1440,20.3,42.4
	>> Kill murlocs for the gem, the drop rate can be very low.
    .complete 1023,1 --Collect Glowing Gem (x1)
step
    .goto 1440,14.7,31.3
.target Talen
>>Talk to |cRXP_FRIENDLY_Talen|r
    .accept 1007 >> Accept The Ancient Statuette
step
    #label nagas
    #sticky
    .goto 1440,13.8,29.1,0,0
	>>Kill nagas around the coast, loot them for their heads
    .complete 1008,1 --Collect Wrathtail Head (x20)
step
    .goto 1440,14.2,20.6
	>> Head to the Ancient Statuette and loot it off the ground. Kill naga en route but don't go out of your way for them, you have plenty of chances for heads.
    .complete 1007,1 --Collect Ancient Statuette (x1)
step
    .goto 1440,14.790,31.294
	>> Kill naga en route but don't go out of your way for them.
>>Talk to |cRXP_FRIENDLY_Talen|r
    .turnin 1007 >> Turn in The Ancient Statuette
    .timer 25,The Ancient Statuette RP
.target Talen
    .accept 1009 >> Accept Ruuzel
step
    .goto 1440,7.0,13.4
	>>Head to the island north and kill Ruuzel
	>> This fight can be hard, focus down one or two of her adds then reset if needed.
    .complete 1009,1 --Collect Ring of Zoram (x1)
step
    .goto 1414,43.97,35.31,20,0
    .goto 1414,43.80,35.18,20,0
	.goto 1414,43.94,34.89,20,0
	.goto 1414,43.91,34.58,20,0
	.goto 1414,44.02,34.58,20,0
	.goto 1414,44.16,34.85
    >>Enter the temple building that leads to Blackfathom Deeps and kill nagas/satyrs. Loot them for brain stems.
    .complete 1275,1
step
    #requires nagas
    .goto 1440,14.790,31.294
.target Talen
>>Talk to |cRXP_FRIENDLY_Talen|r
    .turnin 1009 >> Turn in Ruuzel
step
    #role A,B,C
    .goto 1414,44.16,34.85
    >>Enter Blackfathom Deeps with your group: the temple on the Zoram Strand, then dive down to the entrance
step
    #role A,B,C
    >>Kill the Twilight's Hammer cultists in the dungeon for Twilight Pendants
    .complete 1199,1 --Collect Twilight Pendant (x10)
    .mob Twilight Acolyte
    .mob Twilight Reaver
    .mob Twilight Aquamancer
    .mob Twilight Loreseeker
    .mob Twilight Shadowmage
    .mob Twilight Elementalist
step
    #role A,B,C
    >>Find the Lorgalis Manuscript underwater in the flooded halls
    .complete 971,1 --Collect Lorgalis Manuscript (x1)
    .isOnQuest 971
step
    #role A,B,C
    .turnin 1198 >> Turn in In Search of Thaelrid
    .accept 1200 >> Accept Blackfathom Villainy
    >>Talk to |cRXP_FRIENDLY_Argent Guard Thaelrid|r, partway through the dungeon
step
    #role A,B,C
    >>Kill Twilight Lord Kelris at the Moonshrine for his head
    .complete 1200,1 --Collect Head of Kelris (x1)
    .mob Twilight Lord Kelris
step << Druid
    #completewith next
    >>Teleport to Moonglade
    .goto 1450,52.4,40.6
    .trainer >> Train your spells
step
    .goto 1440,36.618,49.581
    .hs >> Hearth to Astranaar
step
#xprate <1.7
    .isOnQuest 1023
    .goto 1440,36.618,49.581
.target Raene Wolfrunner
>>Talk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .turnin 1023 >> Turn in Raene's Cleansing
step
#xprate <1.2
    .goto 1440,36.618,49.581
.target Raene Wolfrunner
>>Talk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .accept 1025 >> Accept An Aggressive Defense
step
    .goto 1440,37.3,51.8
.target Pelturas Whitemoon
>>Talk to |cRXP_FRIENDLY_Pelturas Whitemoon|r
    .turnin 1034 >> Turn in The Ruins of Stardust
step
    .goto 1440,34.7,48.9
.target Shindrell Swiftfire
>>Talk to |cRXP_FRIENDLY_Shindrell Swiftfire|r
    .turnin 1008 >> Turn in The Zoram Strand
step
#xprate <1.2
    >>Kill the mobs for An Aggressive Defense
    .goto 1440,49.9,60.8,40,0
    .goto 1440,56.9,63.7,40,0
    .goto 1440,49.9,60.8
    .complete 1025,1 --Kill Foulweald Den Watcher (x1)
    .complete 1025,2 --Kill Foulweald Ursa (x2)
    .complete 1025,3 --Kill Foulweald Totemic (x10)
    .complete 1025,4 --Kill Foulweald Warrior (x12)
step
#xprate <1.2
    .goto 1440,49.796,67.211
.target Sentinel Velene Starstrike
>>Talk to |cRXP_FRIENDLY_Sentinel Velene Starstrike|r
    .accept 1016 >> Accept Elemental Bracers
step
#xprate <1.2
    >>Kill all water elementals on the island/in the water for Intact Elemental Bracers. When you have 5, right click the Divining Scroll
    .goto 1440,48.0,69.9
    .complete 1016,1 --Collect Divined Scroll (x1)
step
#xprate <1.2
    .goto 1440,49.796,67.211
.target Sentinel Velene Starstrike
>>Talk to |cRXP_FRIENDLY_Sentinel Velene Starstrike|r
    .turnin 1016 >> Turn in Elemental Bracers
step
#xprate <1.2
    .goto 1440,36.618,49.581
.target Raene Wolfrunner
>>Talk to |cRXP_FRIENDLY_Raene Wolfrunner|r
    .turnin 1025 >> Turn in An Aggressive Defense
    .isQuestComplete 1025
step
    .goto 1440,34.40,48.00
    .fly Auberdine>> Fly to Auberdine
step
    .isQuestComplete 4740
    .goto 1439,37.706,43.390
.target Sentinel Glynda Nal'Shea
>>Talk to |cRXP_FRIENDLY_Sentinel Glynda Nal'Shea|r
    .turnin 4740 >> Turn in WANTED: Murkdeep!
step
    .goto 1439,38.36,43.07
.target Gershala Nightwhisper
>>Talk to |cRXP_FRIENDLY_Gershala Nightwhisper|r
    .turnin 1275 >> Turn in Researching the Corruption
    .isQuestComplete 1275
step
    .isOnQuest 994
    .goto 1439,39.3,43.4
.target Terenthis
>>Talk to |cRXP_FRIENDLY_Terenthis|r
    .turnin 994 >> Turn in Escape Through Force
step
    .isOnQuest 731
    .goto 1439,37.5,41.9
>>Talk to |cRXP_FRIENDLY_Archaeologist Hollee|r
    .turnin 731 >> Turn in The Absent Minded Prospector
.target Archaeologist Hollee
	.accept 741 >> Accept The Absent Minded Prospector << !Hunter !NightElf !Rogue
step
    .goto 1439,37.4,41.8
    .accept 98461 >> Accept Unrequited Love
    .target Archaeologist Hollee
step << !Hunter !NightElf !Rogue
    .goto 1439,33.1,39.9
    .isOnQuest 741
    .zone Teldrassil>>Take the boat to Teldrassil
step << !Hunter !NightElf !Rogue
	.goto 1438,23.703,64.511
    .isOnQuest 741
>>Talk to |cRXP_FRIENDLY_Chief Archaeologist Greywhisker|r
	.turnin 741 >> Turn in The Absent Minded Prospector
.target Chief Archaeologist Greywhisker
	.accept 942 >> Accept The Absent Minded Prospector
step << Priest
    .goto 1438,37.89,82.73
    .trainer >> Train your class spells
    .isOnQuest 942
step << Mage/Priest/Warlock
    .isOnQuest 942
	.goto 1438,29.2,56.7
    .train 227 >> Train Staves
step
    #role A,B,C
    .goto 1439,33.2,39.9
    .zone Teldrassil >> Take the boat to Teldrassil
    .zoneskip Darnassus
step
    #role A,B,C
    .goto 1438/1,968.90,8795.34
    .zone Darnassus >> Take the purple portal into Darnassus
step
    #role A,B,C
    .goto 1457,55.24,23.99
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Argent Guard Manados|r
    .target Argent Guard Manados
    .turnin 1199 >> Turn in Twilight Falls
step
    #role A,B,C
    .goto 1457,56.16,24.39
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Dawnwatcher Selgorm|r
    .target Dawnwatcher Selgorm
    .turnin 1200 >> Turn in Blackfathom Villainy
step << !Hunter !NightElf !Rogue
    .isOnQuest 942
    .goto 1457,31.0,41.5,30,0
    .goto 1438,58.399,94.016
    >> Exit Darnassus through the purple portal
    .fp Rut'theran >> Get the Rut'theran Village flight path
step << !Hunter !NightElf !Rogue
    .isOnQuest 942
    .goto 1438,58.399,94.016
    .fly Auberdine >>Fly back to Auberdine
step
    #role A,B,C
    .goto 1438,58.399,94.016
    .fly Auberdine >> Fly to Auberdine
    .isNotOnQuest 942]])
