-- Headstart: 23-24 Wetlands. GENERATED by tools/fork_rxp.py from RestedXP's guide (RestedXP Alliance 23-30.lua,
-- CC BY-NC-SA 4.0); only the changes in that script are ours. Do not edit by hand.
local _, YR = ...

YR:ShipGuide("23_24_wetlands", [[
#forever
<< Alliance
#name 23-24 Wetlands
#version 1
#group Headstart Launch (A)
#groupid RXP-SRGCE-A1
#next 24-27 Redridge/Duskwood
#xprate <1.5

step << !Human
    .goto 1453,71.053,72.488
    .fp Stormwind >> Learn the Stormwind Flight Path
step << Rogue
	.goto 1453,80.260,68.541
    .train 1804>>Make sure to train lockpicking
step << Hunter/Warrior/Paladin/Shaman/Rogue
	.goto 1455,61.34,89.25
	.train 197 >> Train 2H Axes << !Rogue
	.train 266 >> Train Guns << Hunter/Warrior/Rogue
    .train 199 >> Train 2H Maces << Warrior/Shaman
    .train 54 >> Train Maces << Rogue/Shaman
    .train 44 >> Train Axes << Shaman
step
    #role A,B,C
    .goto 1455,50.83,5.62
    >>|Tinterface/worldmap/chatbubble_64grey.blp:20|tTalk to |cRXP_FRIENDLY_Gerrig Bonegrip|r
    .target Gerrig Bonegrip
    .turnin 971 >> Turn in Knowledge in the Deeps
    .isOnQuest 971
step
    .goto 1437,8.310,58.533
.target Karl Boran
>>Talk to |cRXP_FRIENDLY_Karl Boran|r
    .accept 279 >> Accept Claws from the Deep
step
    .goto 1437,8.5,58.5
    .accept 98189 >> Accept Return the Statuette
    .target Karl Boran
step
    .goto 1437,9.8,57.4
    .turnin 98189 >> Turn in Return the Statuette
    .target Captain Stoutfist
step
    .goto 1437,10.0,56.8
    .accept 98197 >> Accept Spoils of War
    .target Valstag Ironjaw
step
    .goto 1437,11.7,58.5
    .accept 98282 >> Accept Alchemical Hazards
    .target Caitlin Grassman
step
    .goto 1437,8.0,54.0
    >>Pick up |cRXP_PICK_Khaz Modan Timber|r and |cRXP_PICK_Khaz Modan Iron|r from the piles in and around Menethil Harbor
    .complete 98197,1
    .complete 98197,2
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .accept 484 >> Accept Young Crocolisk Skins
step
    .goto 1437,10.8,59.6
.target First Mate Fitzsimmons
>>Talk to |cRXP_FRIENDLY_First Mate Fitzsimmons|r
    .accept 288 >> Accept The Third Fleet
    .accept 463 >> Accept The Greenwarden
step
    .goto 1437,10.7,60.9
	>> Buy a Flagon of Mead from the Innkeeper
    .complete 288,1 --Collect Flagon of Mead (x1)
step
    .goto 1437,10.84,60.43
	>>Go upstairs and talk to Archaeologist Flagongut
>>Talk to |cRXP_FRIENDLY_Archaeologist Flagongut|r
	.turnin 942 >>Turn in The Absent Minded Prospector
.target Archaeologist Flagongut
	.accept 943 >>Accept The Absent Minded Prospector
    .isQuestTurnedIn 741
step
    .goto 1437,10.8,59.7
.target First Mate Fitzsimmons
>>Talk to |cRXP_FRIENDLY_First Mate Fitzsimmons|r
    .turnin 288 >> Turn in The Third Fleet
step << Hunter
    .goto 1437,11.1,58.3
    .vendor >> Repair and restock on arrows
step
    .goto 1437,11.7,58.0
.target Sida
>>Talk to |cRXP_FRIENDLY_Sida|r
    .accept 470 >> Accept Digging Through the Ooze
step
    #sticky
    #completewith exit1
    .vendor 1448>>Head to the keep and buy a Bronze Tube from Neal Allen (limited supply), skip this step if he doesn't have it or if you already have one
    .goto 1437,10.6,56.8
    .collect 4371,1,175,1,1
    .bronzetube
step
    .goto 1437,9.9,57.4
	>>Go upstairs inside the keep
.target Captain Stoutfist
>>Talk to |cRXP_FRIENDLY_Captain Stoutfist|r
    .accept 464 >> Accept War Banners
step
    .goto 1437,11.503,52.134
.target Tarrel Rockweaver
>>Talk to |cRXP_FRIENDLY_Tarrel Rockweaver|r
    .accept 305 >> Accept In Search of The Excavation Team
step
    .goto 1437,11.4,52.2
    .turnin 98461 >> Turn in Unrequited Love
    .target Tarrel Rockweaver
    .isOnQuest 98461
step
	#sticky
	#label crocs
    #completewith endofcrocc
	>> Kill Young Wetlands Crocolisks between quests. Loot them for their Skin
    .complete 484,1 --Collect Young Crocolisk Skin (x4)

step
    #label exit1
    .goto 1437,14.1,41.5,70,0
    .goto 1437,16.7,39.7,70,0
    .goto 1437,18.8,40.0
    >>Kill Gobbler, he patrols around the southern murloc camps
    .complete 279,2 --Collect Gobbler's Head (x1)
    .complete 279,1 --Kill Bluegill Murloc (x12)
	.unitscan Gobbler
step
    #sticky
    #completewith next
    .vendor 2682>>Buy a Bronze Tube from Fradd Swiftgear (limited supply), skip this step if he doesn't have it or if you already have one
    .goto 1437,26.4,25.8
    .collect 4371,1,175,1,1
	.bronzetube
step
    #xprate <1.5
	.goto 1437,34.3,41.2,60,0
    .goto 1437,38.179,50.889
.target Ormer Ironbraid
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .accept 294 >> Accept Ormer's Revenge
step
    .goto 1437,38.8,52.3
>>Talk to |cRXP_FRIENDLY_Merrin Rockweaver|r
    .turnin 305 >> Turn in In Search of The Excavation Team
.target Merrin Rockweaver
    .accept 306 >> Accept In Search of The Excavation Team
step << Hunter/Warlock
    .goto 1437,24.7,48.6
	>> Kill raptors in the area
    .complete 294,1 --Kill Mottled Raptor (x10)
    .complete 294,2 --Kill Mottled Screecher (x10)
step << Hunter/Warlock
	.goto 1437,34.3,41.4,80,0
    .goto 1437,38.179,50.889
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .turnin 294 >> Turn in Ormer's Revenge
.target Ormer Ironbraid
    .accept 295 >> Accept Ormer's Revenge
step << Hunter/Warlock
	.goto 1437,34.3,41.4,80,0
    .goto 1437,34.6,48.0
	>> Kill raptors in the area
    .complete 295,1 --Kill Mottled Scytheclaw (x10)
    .complete 295,2 --Kill Mottled Razormaw (x10)
step << Hunter/Warlock
    .goto 1437,38.179,50.889
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .turnin 295 >> Turn in Ormer's Revenge
.target Ormer Ironbraid
    .accept 296 >> Accept Ormer's Revenge
step << Hunter/Warlock
    .goto 1437,31.5,48.9,50,0
    .goto 1437,33.3,51.5
	>>Kill Sarltooth atop the hill. Loot him for his Talon. Be careful as he Thrashes and has a 6 minute respawn.
    *Note: He can very very rarely be found patroling the quarry below.
    .complete 296,1 --Collect Sarltooth's Talon (x1)
step << Hunter/Warlock
    .goto 1437,38.179,50.889
.target Ormer Ironbraid
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .turnin 296 >> Turn in Ormer's Revenge
step
    .goto 1437,49.5,61.5
    >>Thelgen Rock: kill |cRXP_ENEMY_Leech Stalkers|r and |cRXP_ENEMY_Cave Stalkers|r until one drops an |cRXP_LOOT_Unruptured Stalker Gland|r
    .complete 98282,1
    .mob Leech Stalker
    .mob Cave Stalker
step
	.goto 1437,34.3,41.2,60,0
    .goto 1437,44.8,43.9
	>>Kill Dragonmaw Orcs
    .complete 464,1 --Collect Dragonmaw War Banner (x8)
step
    .goto 1437,49.915,39.367
.target Einar Stonegrip
>>Talk to |cRXP_FRIENDLY_Einar Stonegrip|r
    .accept 469 >> Accept Daily Delivery
step << Warrior
    #sticky
    #completewith next
    .goto 1437,50.2,37.8
    .vendor 8305>>Check the herb vendor and buy some Liferoot, you will need 8 for a quest later, skip this step if you already have it
    .collect 3357,8,0,1,1 --Collect Liferoot (x8)
    #xprate <1.5
step
    #requires crocs
    .goto 1437,56.371,40.401
.target Rethiel the Greenwarden
>>Talk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .turnin 463 >> Turn in The Greenwarden
step
    .goto 1437,56.371,40.401
.target Rethiel the Greenwarden
>>Talk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .accept 276 >> Accept Tramping Paws
    .maxlevel 23
step
    .goto 1437,63.9,62.7,70,0
    .goto 1437,62.4,69.5,70,0
    .goto 1437,61.5,72.2,70,0
    .goto 1437,55.7,75.1
	>>Kill Mosshide Gnolls and Mongrels in the area. The gnolls are more commonly found outside the camps
    .complete 276,1 --Kill Mosshide Gnoll (x15)
    .complete 276,2 --Kill Mosshide Mongrel (x10)
    .isOnQuest 276
step
    #requires crocs
    .goto 1437,56.4,40.3
.target Rethiel the Greenwarden
>>Talk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .turnin 276 >> Turn in Tramping Paws
    .isQuestComplete 276
step
    #label endofcrocc
    .goto 1437,56.4,40.3
.target Rethiel the Greenwarden
>>Talk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .accept 277 >> Accept Fire Taboo
    .isQuestTurnedIn 276
step << NightElf
    #completewith next
    .goto 1437,53.7,72.3,75 >> The path to Loch Modan starts here
step << NightElf
    .goto 1432,25.4,10.6
    .zone Loch Modan >> Cross the tunnel into Loch Modan
step << NightElf
    .goto 1432,46.0,13.3
.target Chief Engineer Hinderweir VII
>>Talk to |cRXP_FRIENDLY_Chief Engineer Hinderweir VII|r
    .accept 250 >> Accept A Dark Threat Looms
    .maxlevel 23
step << NightElf
    .goto 1432,56.1,13.3
    >>Click on the Suspicious Barrel
    .turnin 250 >> Turn in A Dark Threat Looms
    .accept 199 >> Accept A Dark Threat Looms
    .maxlevel 23
step << NightElf
    .goto 1432,46.0,13.3
.target Chief Engineer Hinderweir VII
>>Talk to |cRXP_FRIENDLY_Chief Engineer Hinderweir VII|r
    .turnin 199 >> Turn in A Dark Threat Looms
    .isOnQuest 199
step << NightElf
    .goto 1432,33.938,50.954
    .fp Thelsamar >> Get the Thelsamar flight path
step
    .zoneskip Wetlands,1
    .goto 1437,8.4,58.5
>>Talk to |cRXP_FRIENDLY_Karl Boran|r
    .turnin 279 >> Turn in Claws from the Deep
.target Karl Boran
    .accept 281 >> Accept Reclaiming Goods
step
    .zoneskip Wetlands,1
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 469 >> Turn in Daily Delivery
    .isOnQuest 469
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 484 >> Turn in Young Crocolisk Skins
    .isOnQuest 484
    .zoneskip Wetlands,1
step
    .goto 1437,10.0,56.8
    .turnin 98197 >> Turn in Spoils of War
    .target Valstag Ironjaw
    .isQuestComplete 98197
step
    .goto 1437,11.7,58.5
    .turnin 98282 >> Turn in Alchemical Hazards
    .target Caitlin Grassman
    .isQuestComplete 98282
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .accept 471 >> Accept Apprentice's Duties
    .isQuestTurnedIn 484
    .zoneskip Wetlands,1
step
    .zoneskip Wetlands,1
    .goto 1437,9.5,59.7
    >> Hearth if your hearthstone is set to Stormwind
    .fly Stormwind >> Fly to Stormwind City
]])
