-- Headstart: 24-27 Redridge/Duskwood. GENERATED by tools/fork_rxp.py from RestedXP's guide (RestedXP Alliance 23-30.lua,
-- CC BY-NC-SA 4.0); only the changes in that script are ours. Do not edit by hand.
local _, YR = ...

YR:ShipGuide("24_27_redridge_duskwood", [[
#forever
<< Alliance
#name 24-27 Redridge/Duskwood
#version 1
#group Headstart Launch (A)
#groupid RXP-SRGCE-A1
#next 27-30 Wetlands/Hillsbrad;28-30 Duskwood
step << Warrior
    #sticky
    #completewith exit
    .goto 1453,64.1,61.2,0
    .goto 1453,46.7,79.0,0
    >>Check the the AH, the flower shop at the trade district and the alchemy shop at the mage district and buy some Liferoot, you will need 8 for a quest later, skip this step if you already have it
    .collect 3357,8 --Collect Liferoot (x8)
    #xprate <1.5
step << Paladin
	.goto 1453,38.6,32.8
	.trainer >> Train your class spells
step << Priest
	.goto 1453,38.5,26.8
	.trainer >> Train your class spells
step << Paladin
    .goto 1453,40.1,30.0
    >>Speak to Duthorian Rall and right click on the Tome of Valor provided
    .accept 1649 >>Accept The Tome of Valor
>>Talk to |cRXP_FRIENDLY_Duthorian Rall|r
    .turnin 1649 >>Turn in The Tome of Valor
.target Duthorian Rall
    .accept 1650 >>Accept The Tome of Valor
step << Warlock
    .goto 1453,25.3,78.7
    .trainer >> Train your class spells
step << Warlock
    .isOnQuest 1738
    .goto 1453,25.3,78.7
>>Talk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .turnin 1738 >>Turn in Heartswood
.target Gakin the Darkbinder
    .accept 1739 >>Accept The Binding
step << Warlock
    .isOnQuest 1739
    .goto 1453,25.2,77.5
    >>Go down into the crypt and use the quest item provided at the summoning circle
    .complete 1739,1 --Summoned Succubus (1)
step << Warlock
    .isQuestComplete 1739
    .goto 1453,25.4,78.7
.target Gakin the Darkbinder
>>Talk to |cRXP_FRIENDLY_Gakin the Darkbinder|r
    .turnin 1739 >>Turn in The Binding
step << Mage
    .goto 1453,39.6,79.6
    .train 3561>>Train Teleport: Stormwind
    .trainer >> Train your class spells
step << Rogue
    >> Make sure you train lockpicking and pickpocketing
	.goto 1453,74.6,52.8
	.trainer >> Train your class spells
step << Warrior
	.goto 1453,78.6,45.8
	.trainer >> Go upstairs. Train your class spells
step << Hunter
	.goto 1453,61.7,15.4
	.train 14323 >> Train your class spells
step
    .goto 1453,53.62,59.76,30,0
    .goto 1453,55.25,7.08
    .vendor 5519>> Check Billibub in the Dwarven District for a Bronze Tube. Buy one if it's available
    .collect 4371,1,175,1,1
    .bronzetube
step << Shaman
	.goto 1453,61.9,84.0
	.trainer >> Train your class spells
step << Human Paladin/Human Warlock
	.goto 1453,62.5,62.3,30,0
	.goto 1453,66.3,62.1
    .fly Redridge >> Fly to Redridge Mountains
    .zoneskip Elwynn Forest
step << !Human
    .goto 1429,65.2,69.8
	>>Head to the top of the Tower of Azora. You do NOT need to get the Stormwind Flight Path. We will get it later.
.target Theocritus
>>Talk to |cRXP_FRIENDLY_Theocritus|r
    .accept 94 >> Accept A Watchful Eye
step
    #label exit
    .goto 1433,17.4,69.6
	>>Talk to Guard Parker in Redridge Mountains
.target Guard Parker
>>Talk to |cRXP_FRIENDLY_Guard Parker|r
    .accept 244 >> Accept Encroaching Gnolls
step
	#sticky
	#label LakeshireFP
	.goto 1433,30.5,59.4,-1
    .fp Redridge >> Get the Redridge Mountains flight path
step
    .goto 1433,30.8,60.1,-1
.target Deputy Feldon
>>Talk to |cRXP_FRIENDLY_Deputy Feldon|r
    .turnin 244 >> Turn in Encroaching Gnolls
step
	#requires LakeshireFP
    .goto 1433,33.4,49.1
.target Marshal Marris
>>Talk to |cRXP_FRIENDLY_Marshal Marris|r
    .accept 20 >> Accept Blackrock Menace
step << !Warlock
    >> Head into the town hall
    .goto 1433,29.6,44.3
.target Bailiff Conacher
>>Talk to |cRXP_FRIENDLY_Bailiff Conacher|r
    .accept 91 >> Accept Solomon's Law
step << Hunter
	.goto 1433,28.8,47.3
	.vendor >> Restock on arrows, note you will get level 25 arrows soon.
step
    .goto 1433,27.723,47.381
.target Dockmaster Baren
>>Talk to |cRXP_FRIENDLY_Dockmaster Baren|r
    .accept 127 >> Accept Selling Fish
    .accept 150 >> Accept Murloc Poachers
step
    #sticky
    #label orcs1
    .goto 1433,61.0,43.1
    >>Kill Blackrock orcs
    .complete 20,1 --Collect Battleworn Axe (x10)
step
    .goto 1433,57.3,52.4
	>> Kill murlocs. Loot them for their Sunfish and Fins
    .complete 127,1 --Collect Spotted Sunfish (x10)
    .collect 1468,8,150,1 --Collect Murloc Fin (x8)
step
    #requires orcs1
    .goto 1433,33.6,48.7
.target Marshal Marris
>>Talk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 20 >> Turn in Blackrock Menace
step
    .goto 1433,27.8,47.4
.target Dockmaster Baren
>>Talk to |cRXP_FRIENDLY_Dockmaster Baren|r
    .turnin 127 >> Turn in Selling Fish
    .turnin 150 >> Turn in Murloc Poachers
step
    .goto 1433,26.7,46.5
	>>Click on the wanted poster outside the inn
    .accept 180 >> Accept Wanted: Lieutenant Fangore
step
    .goto 1433,21.858,46.329
.target Martie Jainrose
>>Talk to |cRXP_FRIENDLY_Martie Jainrose|r
    .accept 34 >> Accept An Unwelcome Guest
step
    .goto 1433,15.7,49.4
	>> Kill Bellygrub and loot her for her tusk
    .complete 34,1 --Collect Bellygrub's Tusk (x1)
step
    .goto 1433,21.8,46.4
.target Martie Jainrose
>>Talk to |cRXP_FRIENDLY_Martie Jainrose|r
    .turnin 34 >> Turn in An Unwelcome Guest
step
    >>Run to Duskwood
	.goto 1431,75.7,45.3
.target Madame Eva
>>Talk to |cRXP_FRIENDLY_Madame Eva|r
    .accept 66 >> Accept The Legend of Stalvan
    .accept 101 >> Accept The Totem of Infliction
step << !Rogue
    .goto 1431,73.9,44.5
    .home >> Set your Hearthstone to Darkshire
step
    .goto 1431,73.6,46.8
.target Commander Althea Ebonlocke
>>Talk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    .accept 56 >> Accept The Night Watch
step
    .goto 1431,72.6,46.9
>>Talk to |cRXP_FRIENDLY_Clerk Daltry|r
    .turnin 66 >> Turn in The Legend of Stalvan
.target Clerk Daltry
    .accept 67 >> Accept The Legend of Stalvan
step
    .goto 1431,75.3,48.6
.target Elaine Carevin
>>Talk to |cRXP_FRIENDLY_Elaine Carevin|r
    .accept 163 >> Accept Raven Hill
    .accept 164 >> Accept Deliveries to Sven
    .accept 165 >> Accept The Hermit
step
    .goto 1431,75.4,48.0
.target Calor
>>Talk to |cRXP_FRIENDLY_Calor|r
    .accept 173 >> Accept Worgen in the Woods
step
    .goto 1431,77.8,48.2
    .vendor >>Buy a bronze tube from Herble Baubbletump (limited supply) if you don't have one
    .bronzetube
step
    .goto 1431,79.8,47.9
.target Viktori Prism'Antras
>>Talk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 174 >> Accept Look To The Stars
    .turnin 174 >> Turn in Look To The Stars
    .itemcount 4371,<1
step << Rogue
    .goto 1431,77.5,44.4
    .fp Duskwood >> Get the Duskwood flight point
step
    .goto 1431,79.8,47.9
.target Viktori Prism'Antras
>>Talk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .accept 175 >> Accept Look To The Stars
    .isQuestTurnedIn 174
step
	#sticky
	#completewith HistoryB
	.use 2794 >>Keep an eye out for the book (zone-wide drop). You'll need this for later
	.collect 2794,1,337
	.accept 337 >> Accept An Old History Book
step
    .goto 1431,82.0,59.0
>>Talk to |cRXP_FRIENDLY_Blind Mary|r
    .turnin 175 >> Turn in Look To The Stars
.target Blind Mary
    .accept 177 >> Accept Look To The Stars
    .isQuestTurnedIn 174
step
    .goto 1431,80.9,71.8
    >>Kill the Insane Ghoul at the chapel. He can patrol outside as well.
    .complete 177,1 --Collect Mary's Looking Glass (x1)
    .isQuestTurnedIn 174
	.unitscan Insane Ghoul
step
    .goto 1431,79.3,70.3
    >> Kill skeletal mobs in the area
    .complete 56,1 --Kill Skeletal Warrior (x8)
    .complete 56,2 --Kill Skeletal Mage (x6)
step
    .goto 1431,18.4,56.6
>>Talk to |cRXP_FRIENDLY_Jitters|r
    .turnin 163 >> Turn in Raven Hill
.target Jitters
    .accept 5 >> Accept Jitters' Growling Gut
step
    .goto 1431,7.781,34.069
>>Talk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 164 >> Turn in Deliveries to Sven
.target Sven Yorgen
    .accept 95 >> Accept Sven's Revenge
step
    .goto 1431,7.7,33.3
.target Lars
>>Talk to |cRXP_FRIENDLY_Lars|r
    .accept 226 >> Accept Wolves at Our Heels
    .maxlevel 26
step
    .goto 1431,28.0,31.5
>>Talk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 165 >> Turn in The Hermit
.target Abercrombie
    .accept 148 >> Accept Supplies from Darkshire
step
    .isOnQuest 226
    >>Run up the coast killing wolves
    .xp 25,1
    .goto 1431,17.6,24.6
    .complete 226,1 --Kill Starving Dire Wolf (x12)
    .complete 226,2 --Kill Rabid Dire Wolf (x8)
step << Rogue/Druid
    #label HistoryB
	.goto 1431,17.7,29.1
    .accept 225 >> Accept The Weathered Grave
    .xp <25,1
step << !Rogue !Druid
	.goto 1431,17.7,29.1
    .accept 225 >> Accept The Weathered Grave
    .xp <25,1
step << Rogue/Druid
    .goto 1436,56.6,52.6
    .fp Sentinel >> Get the Sentinel Hill flight path
step << Rogue/Druid
    .goto 1436,41.5,66.8
    .turnin 67 >> Turn in The Legend of Stalvan
    .accept 68 >> Accept The Legend of Stalvan
step << Rogue/Druid
    #sticky
    #completewith next
    .hs >> Hearth back to town
step << !Rogue !Druid !Priest !Warlock
    .goto 1431,60.8,29.7
	>>Grind your way back to eastern Duskwood. If killing Shadow Weavers is too difficult right now skip this step, you will complete it later
    .complete 173,1 --Kill Nightbane Shadow Weaver (x6)
step
    .goto 1431,73.8,43.3
>>Talk to |cRXP_FRIENDLY_Chef Grual|r
    .turnin 5 >> Turn in Jitters' Growling Gut
.target Chef Grual
    .accept 93 >> Accept Dusky Crab Cakes
step
    .goto 1431,73.6,46.8
>>Talk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    .turnin 56 >> Turn in The Night Watch
.target Commander Althea Ebonlocke
    .accept 57 >> Accept The Night Watch
step
    .goto 1431,72.642,47.613
.target Sirra Von'Indi
>>Talk to |cRXP_FRIENDLY_Sirra Von'Indi|r
    .turnin 225 >> Turn in The Weathered Grave
    .isOnQuest 225
step
.target Sirra Von'Indi
>>Talk to |cRXP_FRIENDLY_Sirra Von'Indi|r
    .accept 227 >> Accept Morgan Ladimore
    .goto 1431,72.642,47.613
>>Talk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    .turnin 227 >> Turn in Morgan Ladimore
    .goto 1431,73.5,46.9
.target Commander Althea Ebonlocke
    .accept 228 >> Accept Mor'Ladim
    .goto 1431,73.5,46.9
    .isQuestTurnedIn 225
step
	#sticky
	#completewith next
	.destroy 2154 >> You can delete "The Story of Morgan Ladimore" from your inventory, as it's not needed
step
    .goto 1431,75.7,45.3
>>Talk to |cRXP_FRIENDLY_Madame Eva|r
    .turnin 148 >> Turn in Supplies from Darkshire
.target Madame Eva
    .accept 149 >> Accept Ghost Hair Thread
step
    .goto 1431,75.3,47.9
>>Talk to |cRXP_FRIENDLY_Calor|r
    .turnin 173 >> Turn in Worgen in the Woods
.target Calor
    .accept 221 >> Accept Worgen in the Woods
    .isQuestComplete 173
step
    #label HistoryB
	.goto 1431,79.8,47.8
>>Talk to |cRXP_FRIENDLY_Viktori Prism'Antras|r
    .turnin 177 >> Turn in Look To The Stars
.target Viktori Prism'Antras
    .accept 181 >> Accept Look To The Stars
    .isQuestTurnedIn 174
step
	#sticky
	#completewith HistoryB2
	>>Keep an eye out for Old History book (zone-wide drop). You'll need this for later
	.collect 2794,1,337
	.accept 337 >> Accept An Old History Book
step
    .goto 1431,81.9,59.1
>>Talk to |cRXP_FRIENDLY_Blind Mary|r
    .turnin 149 >> Turn in Ghost Hair Thread
.target Blind Mary
    .accept 154 >> Accept Return the Comb
step
    .goto 1431,75.7,45.3
>>Talk to |cRXP_FRIENDLY_Madame Eva|r
    .turnin 154 >> Turn in Return the Comb
.target Madame Eva
    .accept 157 >> Accept Deliver the Thread
step
    .goto 1431,49.9,77.8
    .turnin 95 >> Turn in Sven's Revenge
    .accept 230 >> Accept Sven's Camp
step
	#label spiders
	#sticky
	#completewith spiderend12
	>>Kill spiders in duskwood
    .complete 93,1 --Collect Gooey Spider Leg (x6)
	.maxlevel 27
step
	.goto 1431,17.7,29.1
    .accept 225 >> Accept The Weathered Grave
step
    .goto 1431,28.0,31.5
>>Talk to |cRXP_FRIENDLY_Abercrombie|r
    .turnin 157 >> Turn in Deliver the Thread
.target Abercrombie
    .accept 158 >> Accept Zombie Juice
step
    .goto 1431,17.6,24.6
    .complete 226,1 --Kill Starving Dire Wolf (x12)
    .complete 226,2 --Kill Rabid Dire Wolf (x8)
    .isOnQuest 226
step << Hunter/Paladin
    .goto 1431,19.7,39.7
    >>Kill the level 30 elite roaming the cemetery. Kite him around the big trees in the area.
    >> Run away and heal when he enrages, use the big trees to make space. Don't try to tank him during the enrage << Paladin
    .complete 228,1 --Collect Mor'Ladim's Skull (x1)
    .isOnQuest 228
step
    .goto 1431,7.781,34.069
>>Talk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 230 >> Turn in Sven's Camp
.target Sven Yorgen
    .accept 262 >> Accept The Shadowy Figure
step
    #label HistoryB2
	.goto 1431,7.7,33.3
.target Lars
>>Talk to |cRXP_FRIENDLY_Lars|r
    .turnin 226 >> Turn in Wolves at Our Heels
    .isOnQuest 226
step << !Rogue !Druid
	#requires spiders
    .goto 1436,56.6,52.6
    .fp Sentinel >> Get the Sentinel Hill flight path
step << !Rogue !Druid
    .goto 1436,41.5,66.8
    .turnin 67 >> Turn in The Legend of Stalvan
    .accept 68 >> Accept The Legend of Stalvan
step << Paladin
    .goto 1436,42.5,88.6
>>Talk to |cRXP_FRIENDLY_Daphne Stilwell|r
    .turnin 1650 >>Turn in The Tome of Valor
.target Daphne Stilwell
    .accept 1651 >>Accept The Tome of Valor
step << Paladin
    .goto 1436,42.5,88.6
    .complete 1651,1 --Protect Daphne Stilwell (1)
>>Talk to |cRXP_FRIENDLY_Daphne Stilwell|r
    .turnin 1651 >>Turn in The Tome of Valor
.target Daphne Stilwell
    .accept 1652 >>Accept The Tome of Valor
step << !Rogue !Druid
    #sticky
    #completewith next
    .hs >> Hearth back to Duskwood
step << Rogue/Druid
	#requires spiders
    .goto 1431,60.8,29.7
	>>Grind your way back to eastern Duskwood
    .complete 173,1 --Kill Nightbane Shadow Weaver (x6)
step
    .goto 1431,75.7,45.3
>>Talk to |cRXP_FRIENDLY_Madame Eva|r
    .turnin 262 >> Turn in The Shadowy Figure
.target Madame Eva
    .accept 265 >> Accept The Shadowy Search Continues
step
    .goto 1431,72.6,46.9
>>Talk to |cRXP_FRIENDLY_Clerk Daltry|r
    .turnin 265 >> Turn in The Shadowy Search Continues
.target Clerk Daltry
    .accept 266 >> Accept Inquire at the Inn
    .turnin 68 >> Turn in The Legend of Stalvan
    .accept 69 >> Accept The Legend of Stalvan
step
    .goto 1431,72.642,47.613
.target Sirra Von'Indi
>>Talk to |cRXP_FRIENDLY_Sirra Von'Indi|r
    .turnin 225 >> Turn in The Weathered Grave
    .isOnQuest 225
step
.target Sirra Von'Indi
>>Talk to |cRXP_FRIENDLY_Sirra Von'Indi|r
    .accept 227 >> Accept Morgan Ladimore
    .goto 1431,72.642,47.613
>>Talk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    .turnin 227 >> Turn in Morgan Ladimore
    .goto 1431,73.5,46.9
.target Commander Althea Ebonlocke
    .accept 228 >> Accept Mor'Ladim
    .goto 1431,73.5,46.9
    .isQuestTurnedIn 225
step
	#completewith next
	.vendor >> Remember to buy level 25 food and water
step
    .goto 1431,73.9,44.4
>>Talk to |cRXP_FRIENDLY_Tavernkeep Smitts|r
    .turnin 158 >> Turn in Zombie Juice
.target Tavernkeep Smitts
    .accept 156 >> Accept Gather Rot Blossoms
    .turnin 266 >> Turn in Inquire at the Inn
    .accept 453 >> Accept Finding the Shadowy Figure
step
    .goto 1431,73.9,43.9
.target Chef Grual
>>Talk to |cRXP_FRIENDLY_Chef Grual|r
    .turnin 93 >> Turn in Dusky Crab Cakes
    .isQuestComplete 93
step
    .goto 1431,73.9,43.9
.target Chef Grual
>>Talk to |cRXP_FRIENDLY_Chef Grual|r
    .accept 240 >> Accept Return to Jitters
    .isQuestTurnedIn 93
step << Hunter/Paladin
	.goto 1431,73.7,46.8
>>Talk to |cRXP_FRIENDLY_Commander Althea Ebonlocke|r
    .turnin 228 >> Turn in Mor'Ladim
.target Commander Althea Ebonlocke
    .accept 229 >> Accept The Daughter Who Lived
step << Hunter/Paladin
    .goto 1431,74.543,46.085
>>Talk to |cRXP_FRIENDLY_Watcher Ladimore|r
    .turnin 229 >> Turn in The Daughter Who Lived
.target Watcher Ladimore
    .accept 231 >> Accept A Daughter's Love
step << !Rogue !Druid
    .isOnQuest 173
    .goto 1431,60.8,29.7
	>>Kill Shadow Weavers above Darkshire
    .complete 173,1 --Kill Nightbane Shadow Weaver (x6)
step
    .goto 1431,75.3,47.9
>>Talk to |cRXP_FRIENDLY_Calor|r
    .turnin 173 >> Turn in Worgen in the Woods
.target Calor
    .accept 221 >> Accept Worgen in the Woods
    .isQuestComplete 173
step
    #label spiderend12
    .goto 1431,77.5,44.3
 .fly Redridge >> Fly to Redridge
step
    #xprate <1.2
    .goto 1433,31.537,57.852
.target Guard Howe
>>Talk to |cRXP_FRIENDLY_Guard Howe|r
    .accept 128 >> Accept Blackrock Bounty
    .maxlevel 26 << Paladin/Hunter
step
    .goto 1433,33.5,49.2
.target Marshal Marris
>>Talk to |cRXP_FRIENDLY_Marshal Marris|r
    .accept 19 >> Accept Tharil'zun
    .accept 115 >> Accept Shadow Magic
step
    .goto 1433,80.3,37.2
	>> Kill Fangore, and loot him for his Paw. Be careful as lots of gnolls patrol around him, he is shadow immune, and can social aggro all gnolls at any time within 40 yards.
    .complete 180,1 --Collect Fangore's Paw (x1)
step
    .isOnQuest 94
    .goto 1433,84.3,46.9
    .turnin 94 >> Turn in A Watchful Eye
step
    .goto 1433,84.3,46.9
    .accept 248 >> Accept Looking Further
    .isQuestTurnedIn 94
step << !Warlock
    .goto 1433,74.2,42.1
	>> Kill gnolls in the area
    .complete 91,1 --Collect Shadowhide Pendant (x10)
step
	#sticky
	#label tharilzun
    .goto 1433,69.2,59.8
	>> Kill Tharil'zun and loot his head.
    .complete 19,1 --Collect Tharil'zun's Head (x1)
step
    .goto 1433,66.6,55.4
	>>Kill Blackrock Shadowcasters. Loot them for Midnight Orbs
    .complete 115,1 --Collect Midnight Orb (x3)
step
    .isOnQuest 248
    .goto 1433,63.2,49.7
	>>Climb to the top of the tower
    .turnin 248 >> Turn in Looking Further
step
    .goto 1433,32.8,6.8
    .complete 128,1 --Kill Blackrock Champion (x15)
    .isOnQuest 128
step
    .goto 1433,33.504,48.969
.target Marshal Marris
>>Talk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 19 >> Turn in Tharil'zun
	.isQuestComplete 19
step
	.goto 1433,33.504,48.969
.target Marshal Marris
>>Talk to |cRXP_FRIENDLY_Marshal Marris|r
    .turnin 115 >> Turn in Shadow Magic
step << !Warlock
    .goto 1433,29.6,44.3
.target Bailiff Conacher
>>Talk to |cRXP_FRIENDLY_Bailiff Conacher|r
    .turnin 91 >> Turn in Solomon's Law
step
    .goto 1433,29.8,44.5
.target Magistrate Solomon
>>Talk to |cRXP_FRIENDLY_Magistrate Solomon|r
    .turnin 180 >> Turn in Wanted: Lieutenant Fangore
step
    .goto 1433,31.6,58.0
.target Guard Howe
>>Talk to |cRXP_FRIENDLY_Guard Howe|r
    .turnin 128 >> Turn in Blackrock Bounty
    .isQuestComplete 128
step
    #completewith fpwfend
	.goto 1433,30.5,59.3
    .fly Westfall>> Fly to Westfall
step
	#sticky
	#completewith HistoryB3
	.use 2794 >>Keep an eye out for Old History book (zone-wide drop). You'll need this for later
	.collect 2794,1,337
	.accept 337 >> Accept An Old History Book
step
    #completewith fpwfend
    .goto 1431,18.4,56.5
>>Talk to |cRXP_FRIENDLY_Jitters|r
    .turnin 453 >> Turn in Finding the Shadowy Figure
.target Jitters
    .accept 268 >> Accept Return to Sven
step
    .goto 1431,18.4,56.5
.target Jitters
>>Talk to |cRXP_FRIENDLY_Jitters|r
    .turnin 240 >> Turn in Return to Jitters
    .isOnQuest 240
step
    .goto 1431,7.7,34.1
>>Talk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 268 >> Turn in Return to Sven
.target Sven Yorgen
    .accept 323 >> Accept Proving Your Worth
step
    #sticky
    #completewith nomoreraidernote
    .goto 1431,16.2,38.8,0
    >> Kill Skeletal Raiders around the crypt and house on the hill as you complete other quests. You typically cannot get all 15 in one go and want to keep them respawning.
    .complete 323,1 --Kill Skeletal Raider (x15)
step << !Hunter !Paladin
    .goto 1431,21.6,45.1
	>> Kill undead in the area and loot them
    .complete 57,1 --Kill Skeletal Fiend (x15)
    .complete 57,2 --Kill Skeletal Horror (x15)
    .complete 156,1 --Collect Rot Blossom (x8)
    .complete 101,3 --Collect Skeleton Finger (x10)
step << Hunter/Paladin
    .goto 1431,17.7,29.2
    >> Click on the gravestone
    .turnin 231 >> Turn in A Daughter's Love
step << Hunter/Paladin
    .goto 1431,21.6,45.1
	>> Kill undead in the area and loot them
    .complete 57,1 --Kill Skeletal Fiend (x15)
    .complete 57,2 --Kill Skeletal Horror (x15)
    .complete 156,1 --Collect Rot Blossom (x8)
    .complete 101,3 --Collect Skeleton Finger (x10)
step
    #label nomoreraidernote
step
    .goto 1431,16.2,38.8
    >>Kill mobs around the crypt, you might need to go inside it to kill the 3 warders you need
    .complete 323,1 --Kill Skeletal Raider (x15)
    .complete 323,2 --Kill Skeletal Healer (x3)
    .complete 323,3 --Kill Skeletal Warder (x3)
step
	 .goto 1431,23.8,35.0
	.xp 27+12000 >> Grind to 12000+/32200xp
step
    .goto 1431,19.7,39.7
    >>Kill the level 30 elite roaming the cemetery. Skip this step if you cannot solo her or find a group.
    >> Run away when he enrages, use the big trees to kite and make space. Don't try to tank him during the enrage
    .unitscan Mor'Ladim
    .complete 228,1 --Collect Mor'Ladim's Skull (x1)
step
    #label HistoryB3
	.goto 1431,7.9,34.1
>>Talk to |cRXP_FRIENDLY_Sven Yorgen|r
    .turnin 323 >> Turn in Proving Your Worth
.target Sven Yorgen
    .accept 269 >> Accept Seeking Wisdom
step
    >> Run to Goldshire
    .goto 1429,43.7,65.9
>>Talk to |cRXP_FRIENDLY_Innkeeper Farley|r
    .turnin 69 >> Turn in The Legend of Stalvan
.target Innkeeper Farley
    .accept 70 >> Accept The Legend of Stalvan
step
    >>Go upstairs in the room behind the rogue trainer. Loot the chest
	.goto 1429,44.2,65.9
    .complete 70,1 --Collect An Undelivered Letter (x1)
step << Shaman
	.goto 1453,61.9,84.0
	.trainer >> Train your class spells
step << Warrior
    .goto 1429,41.087,65.768
    .trainer >> Train your class spells
step << Mage
    .goto 1453,39.6,79.6
	>> Teleport to stormwind
	.trainer >> Train your class spells
step
    #xprate <1.5
    .goto 1453,26.4,78.4
.target Zardeth of the Black Claw
>>Talk to |cRXP_FRIENDLY_Zardeth of the Black Claw|r
    .accept 335 >> Accept A Noble Brew
step << Warlock
    .goto 1453,26.4,78.4
	.trainer >> Train your class spells
step
    .goto 1453,29.8,61.8
>>Talk to |cRXP_FRIENDLY_Caretaker Folsom|r
    .turnin 70 >> Turn in The Legend of Stalvan
.target Caretaker Folsom
    .accept 72 >> Accept The Legend of Stalvan
step
    .goto 1453,29.6,61.7
    .turnin 72 >> Turn in The Legend of Stalvan
    .accept 74 >> Accept The Legend of Stalvan
step <<!Mage
    .goto 1453,40.8,30.8
.target Brother Sarno
>>Talk to |cRXP_FRIENDLY_Brother Sarno|r
    .accept 2923 >> Accept Tinkmaster Overspark
step << Paladin
    .goto 1453,40.0,29.9
>>Talk to |cRXP_FRIENDLY_Duthorian Rall|r
    .turnin 1652 >>Turn in The Tome of Valor
.target Duthorian Rall
    .accept 1653 >>Accept The Test of Righteousness
step
    .goto 1453,39.3,28.0
>>Talk to |cRXP_FRIENDLY_Bishop Farthing|r
    .turnin 269 >> Turn in Seeking Wisdom
.target Bishop Farthing
    .accept 270 >> Accept The Doomed Fleet
step
    #xprate >1.3
    .xp <28,1
    .goto 1453,41.5,31.7
	>>Talk to the patrolling kid
.target Thomas
>>Talk to |cRXP_FRIENDLY_Thomas|r
    .accept 1274 >> Accept The Missing Diplomat
step << Paladin
#xprate <1.5
	.goto 1453,38.6,32.8
	.trainer >> Train your class spells
step << Priest
#xprate <1.5
	.goto 1453,38.5,26.8
	.trainer >> Train your class spells
step << Hunter
#xprate <1.5
	.goto 1453,61.7,15.4
	.trainer >> Train your class spells

]])
