-- Headstart: 27-30 Wetlands/Hillsbrad. GENERATED by tools/fork_rxp.py from RestedXP's guide (RestedXP Alliance 23-30.lua,
-- CC BY-NC-SA 4.0); only the changes in that script are ours. Do not edit by hand.
local _, YR = ...

YR:ShipGuide("27_30_wetlands_hillsbrad", [[
#forever
<< Alliance
#name 27-30 Wetlands/Hillsbrad
#version 1
#group Headstart Launch (A)
#groupid RXP-SRGCE-A1
#next RestedXP Survival Guide (A)\30-32 Duskwood;RestedXP Alliance 20-32\30-32 Duskwood/STV
#xprate <1.5

step <<!Mage
    .goto 1455,69.8,50.1
.target Tinkmaster Overspark
>>Talk to |cRXP_FRIENDLY_Tinkmaster Overspark|r
    .turnin 2923 >> Turn in Tinkmaster Overspark
step << Rogue
    #sticky
    #completewith next
    .trainer >> Train your class spells in Ironforge. Skip if you just trained in Stormwind.
step << Rogue
    .goto 1455,45.2,6.6
    >>Buy the level 31 weapon upgrades (17dps)
    .collect 2520,1
    .collect 2526,1
    >>Skip this step if you can find a better weapon at the Auction House
step << Mage
    #completewith next
    .zone Ironforge >> Teleport to Ironforge
step << Hunter/Warrior/Paladin/Shaman/Rogue
	.goto 1455,61.34,89.25
	.train 197 >> Train 2H Axes << !Rogue
	.train 266 >> Train Guns << Hunter/Warrior/Rogue
    .train 199 >> Train 2H Maces << Warrior/Shaman
    .train 54 >> Train Maces << Rogue/Shaman
    .train 44 >> Train Axes << Shaman
step << Paladin
    .goto 1426,52.5,36.8
    >> Head to the gates of Ironforge
.target Jordan Stilwell
>>Talk to |cRXP_FRIENDLY_Jordan Stilwell|r
    .turnin 1653 >>Turn in The Test of Righteousness
step
	#label end
	.goto 1455,56.2,46.8
    .fly Wetlands>> Fly to Wetlands
step
    .goto 1437,8.4,58.5
>>Talk to |cRXP_FRIENDLY_Karl Boran|r
    .turnin 279 >> Turn in Claws from the Deep
.target Karl Boran
    .accept 281 >> Accept Reclaiming Goods
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 469 >> Turn in Daily Delivery
    .isOnQuest 469
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 484 >> Turn in Young Crocolisk Skins
    .isOnQuest 484
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .accept 471 >> Accept Apprentice's Duties
    .isQuestTurnedIn 484
step
    .goto 1437,10.8,59.6
.target First Mate Fitzsimmons
>>Talk to |cRXP_FRIENDLY_First Mate Fitzsimmons|r
    .accept 289 >> Accept The Cursed Crew
step
    .goto 1437,10.6,60.5
>>Talk to |cRXP_FRIENDLY_Glorin Steelbrow|r
    .turnin 270 >> Turn in The Doomed Fleet
.target Glorin Steelbrow
    .accept 321 >> Accept Lightforge Iron
step
      .goto 1437,10.7,60.9
	>> Restock on food/water if needed.
.home >> Set your Hearthstone to Deepwater Tavern
step
    .goto 1437,10.9,55.9
.target Harlo Barnaby
>>Talk to |cRXP_FRIENDLY_Harlo Barnaby|r
    .accept 472 >> Accept Fall of Dun Modr
step
    .goto 1437,9.9,57.4
>>Talk to |cRXP_FRIENDLY_Captain Stoutfist|r
    .turnin 464 >> Turn in War Banners
.target Captain Stoutfist
    .accept 465 >> Accept Nek'rosh's Gambit
step
    .goto 1437,11.7,58.0
.target Sida
>>Talk to |cRXP_FRIENDLY_Sida|r
    .accept 470 >> Accept Digging Through the Ooze
step
    .goto 1437,11.500,52.174
.target Tarrel Rockweaver
>>Talk to |cRXP_FRIENDLY_Tarrel Rockweaver|r
    .turnin 306 >> Turn in In Search of The Excavation Team
step
    .goto 1437,13.5,41.5
    .turnin 281 >> Turn in Reclaiming Goods
    .accept 284 >> Accept The Search Continues
step
    .goto 1437,13.5,38.4
    .turnin 284 >> Turn in The Search Continues
    .accept 285 >> Accept Search More Hovels
step
    .goto 1437,13.9,34.8
    .turnin 285 >> Turn in Search More Hovels
    .accept 286 >> Accept Return the Statuette
step
    .goto 1437,13.9,30.4
    >>To find Snellig, enter the ship by the hole on the hull close to the shore
	>> The ship to the north usually has more Marines if you're having trouble finding some.
    .complete 289,3 --Collect Snellig's Snuffbox (x1)
    .complete 289,1 --Kill Cursed Sailor (x13)
    .complete 289,2 --Kill Cursed Marine (x5)
step
    .goto 1437,17.8,26.3
	>> Kill Giant Crocolisks along the coast and loot them for skins
    .complete 471,1 --Collect Giant Crocolisk Skin (x6)
    .isQuestTurnedIn 484
step
    .goto 1437,38.179,50.889
.target Ormer Ironbraid
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .accept 294 >> Accept Ormer's Revenge
step
	#label fossil
	#sticky
	#completewith Relu1
	>>Kill raptors in Wetlands
	.complete 943,1
    .isOnQuest 943
step
    .goto 1437,24.7,48.6
    .complete 294,1 --Kill Mottled Raptor (x10)
    .complete 294,2 --Kill Mottled Screecher (x10)
step
    .goto 1437,38.179,50.889
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .turnin 294 >> Turn in Ormer's Revenge
.target Ormer Ironbraid
    .accept 295 >> Accept Ormer's Revenge
step
    .goto 1437,38.8,52.3
>>Talk to |cRXP_FRIENDLY_Merrin Rockweaver|r
    .turnin 305 >> Turn in In Search of The Excavation Team
.target Merrin Rockweaver
step
	.goto 1437,38.81,52.39
.target Prospector Whelgar
>>Talk to |cRXP_FRIENDLY_Prospector Whelgar|r
	.accept 299 >>Accept Uncovering the Past
step
	#label relics
	#sticky
	.goto 1437,34.3,49.5,0
	>>Loot the 4 relics around the dig site
	.complete 299,1
	.complete 299,2
	.complete 299,3
	.complete 299,4
step
    .goto 1437,34.6,48.0
    .complete 295,1 --Kill Mottled Scytheclaw (x10)
    .complete 295,2 --Kill Mottled Razormaw (x10)
step
    .goto 1437,38.179,50.889
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .turnin 295 >> Turn in Ormer's Revenge
.target Ormer Ironbraid
    .accept 296 >> Accept Ormer's Revenge
step
    .goto 1437,31.5,48.9,50,0
    .goto 1437,33.3,51.5
	>>Kill Sarltooth atop the hill. Loot him for his Talon. Be careful as he Thrashes and has a 6 minute respawn
    .complete 296,1 --Collect Sarltooth's Talon (x1)
step
	#requires relics
    .goto 1437,38.179,50.889
.target Ormer Ironbraid
>>Talk to |cRXP_FRIENDLY_Ormer Ironbraid|r
    .turnin 296 >> Turn in Ormer's Revenge
step
	#requires relics
	.goto 1437,38.81,52.39
.target Prospector Whelgar
>>Talk to |cRXP_FRIENDLY_Prospector Whelgar|r
	.turnin 299 >>Turn in Uncovering the Past
step
	#label Relu1
	.goto 1437,38.81,52.39
	>>Loot the fossil on the ground
	.complete 943,2
    .isOnQuest 943
step
	.goto 1437,34.6,48.0
	>>Keep killing raptors until you loot the Stone of Relu
	.complete 943,1
    .isOnQuest 943
step
    .goto 1437,44.2,25.8
    >>Kill slimes around the crypt
    .complete 470,1 --Collect Sida's Bag (x1)
step
    .goto 1437,44.2,33.9
	>>Kill gnolls
    .complete 277,1 --Collect Crude Flint (x9)
    .isQuestTurnedIn 276
step
    .goto 1437,56.3,40.5
>>Talk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .turnin 277 >> Turn in Fire Taboo
.target Rethiel the Greenwarden
    .accept 275 >> Accept Blisters on The Land
    .isQuestTurnedIn 276
step
    .isOnQuest 465
    .goto 1437,47.3,46.9
    .turnin 465 >> Turn in Nek'rosh's Gambit
    .accept 474 >> Accept Defeat Nek'rosh
step
    .goto 1437,49.4,41.8
    .accept 98245 >> Accept Razormaw Needling
    .accept 98246 >> Accept Trying Times
    .target Howin Kindfeather
step
    .isOnQuest 474
    .goto 1437,53.5,54.6
	>> Kill Nek'rosh and loot him for his head
    .complete 474,1 --Collect Nek'rosh's Head (x1)
step
    .goto 1437,64.8,75.3
    >>Loot the tree root at the base of the waterfall
    .complete 335,2 --Collect Musquash Root (x1)
    .isOnQuest 335
step << Druid
    #completewith next
    >>Teleport to Moonglade
    .goto 1450,52.4,40.6
    .trainer 12042 >> Train spells
step
    .hs >> Hearth to Menethil Harbor
step
    .goto 1437,10.8,59.6
>>Talk to |cRXP_FRIENDLY_First Mate Fitzsimmons|r
    .turnin 289 >> Turn in The Cursed Crew
.target First Mate Fitzsimmons
    .accept 290 >> Accept Lifting the Curse
step
    .goto 1437,10.828,60.398
	>>Go upstairs and talk to Archaeologist Flagongut
.target Archaeologist Flagongut
>>Talk to |cRXP_FRIENDLY_Archaeologist Flagongut|r
	.turnin 943 >>Turn in The Absent Minded Prospector
    .isOnQuest 943
step
    .goto 1437,11.7,58.1
.target Sida
>>Talk to |cRXP_FRIENDLY_Sida|r
    .turnin 470 >> Turn in Digging Through the Ooze
    .isQuestComplete 470
step
    .goto 1437,8.310,58.533
.target Karl Boran
>>Talk to |cRXP_FRIENDLY_Karl Boran|r
    .turnin 286 >> Turn in Return the Statuette
step
    .goto 1437,8.6,55.8
.target James Halloran
>>Talk to |cRXP_FRIENDLY_James Halloran|r
    .turnin 471 >> Turn in Apprentice's Duties
    .isQuestTurnedIn 484
step
    .goto 1437,15.5,23.5
    >>Kill Captain Halyndor by entering the ship through the broken mast
    >>|cRXP_WARN_Be careful he can cast|r |T136232:0|t[Ward of the Eye]|cRXP_WARN_ making him|r |cRXP_ENEMY_REFLECT SPELLS|r |cRXP_WARN_for 6 seconds|r
    .complete 290,1 --Collect Intrepid Strongbox Key (x1)
step
    .goto 1437,14.4,24.0
	>> Dive underwater. Theres a hole in the hull of the north side of the ship. Do NOT delete the Cursed Eye of Paleth, it's used for a later quest.
    .turnin 290 >> Turn in Lifting the Curse
    .accept 292 >> Accept The Eye of Paleth
step
	#sticky
    #completewith Nekkywekky
    >>Kill Fen Creepers, they are stealth mobs lurking along the river stream
    .complete 275,1 --Kill Fen Creeper (x8)--O
    .isOnQuest 275
step
    .goto 1437,47.3,46.9
    .turnin 465 >> Turn in Nek'rosh's Gambit
    .accept 474 >> Accept Defeat Nek'rosh
step
    #label Nekkywekky
    .goto 1437,53.5,54.6
	>> Kill Nek'rosh and loot him for his head
    .complete 474,1 --Collect Nek'rosh's Head (x1)
step
    .isOnQuest 275
    .goto 1437,56.4,40.5
	>>Finish off Fen Creepers in the rivers
    .complete 275,1 --Kill Fen Creeper (x8)
step
    .goto 1437,56.4,40.5
.target Rethiel the Greenwarden
>>Talk to |cRXP_FRIENDLY_Rethiel the Greenwarden|r
    .turnin 275 >> Turn in Blisters on The Land
    .isOnQuest 275
step
    .goto 1437,59.9,28.0
    >>Kill |cRXP_ENEMY_Highland Razormaws|r and |cRXP_ENEMY_Elder Razormaws|r for |cRXP_LOOT_Razormaw Incisors|r, and pick up |cRXP_PICK_Perfect Razormaw Eggs|r around them
    .complete 98245,1
    .complete 98246,1
    .mob Highland Razormaw
    .mob Elder Razormaw
    .isOnQuest 98245
step
    .goto 1437,49.4,41.8
    .turnin 98245 >> Turn in Razormaw Needling
    .target Howin Kindfeather
    .isQuestComplete 98245
step
    .goto 1437,49.4,41.8
    .turnin 98246 >> Turn in Trying Times
    .target Howin Kindfeather
    .isQuestComplete 98246
step
    .goto 1437,49.9,18.3
    .turnin -472 >> Turn in Fall of Dun Modr
.target Rhag Garmason
>>Talk to |cRXP_FRIENDLY_Rhag Garmason|r
    .accept 631 >> Accept The Thandol Span
.target Longbraid the Grim
>>Talk to |cRXP_FRIENDLY_Longbraid the Grim|r
    .accept 304 >> Accept A Grim Task
.target Motley Garmason
>>Talk to |cRXP_FRIENDLY_Motley Garmason|r
    .accept 303 >> Accept The Dark Iron War
step
	#sticky
    #label balgaras
    >>Kill Balgaras the Foul, he can spawn in the camp far to the east or inside one of the houses in Dun Modr. Head east after checking Dun Modir. Loot him for his ear.
    .complete 304,1 --Collect Ear of Balgaras (x1)
	.unitscan Balgaras the Foul
    .goto 1437,47.4,15.4,40,0
    .goto 1437,61.8,31.0,80,0
    .goto 1437,46.8,16.0
step--?
    .goto 1437,47.3,16.6
	>> Kill Dark Iron dwarves in the area
    .complete 303,1 --Kill Dark Iron Dwarf (x10)
    .complete 303,2 --Kill Dark Iron Tunneler (x5)
    .complete 303,3 --Kill Dark Iron Saboteur (x5)
    .complete 303,4 --Kill Dark Iron Demolitionist (x5)
step
    #requires balgaras
    .goto 1437,49.7,18.3
.target Motley Garmason
>>Talk to |cRXP_FRIENDLY_Motley Garmason|r
    .turnin 303 >> Turn in The Dark Iron War
.target Longbraid the Grim
>>Talk to |cRXP_FRIENDLY_Longbraid the Grim|r
    .turnin 304 >> Turn in A Grim Task
step
    .goto 1437,51.2,8.0
	>> Go downstairs and click on the dwarf corpse. Ignore all the mobs.
    .turnin 631 >> Turn in The Thandol Span
    .accept 632 >> Accept The Thandol Span
step
    .goto 1437,49.9,18.3
>>Talk to |cRXP_FRIENDLY_Rhag Garmason|r
    .turnin 632 >> Turn in The Thandol Span
.target Rhag Garmason
    .accept 633 >> Accept The Thandol Span
step
    .goto 1417,43.3,92.6
.target Foggy MacKreel
>>Talk to |cRXP_FRIENDLY_Foggy MacKreel|r
    .accept 647 >> Accept MacKreel's Moonshine
    >>You can still get this quest if you don't have any kind of speed increase or slow fall
step
#xprate <1.5
    .goto 1417,44.3,93.0
	.use 4433 >>Jump down and loot the letter from the corpse underwater
    .accept 637 >> Accept Sully Balloo's Letter
step
    #completewith next
    .goto 1417,52.5,90.4,30 >> Swim east toward the ramp here
step
    .goto 1417,48.7,87.9
    .complete 633,1 --Collect Cache of Explosives Destroyed (x1)
step
    .goto 1437,49.9,18.3
>>Talk to |cRXP_FRIENDLY_Rhag Garmason|r
    .turnin 633 >> Turn in The Thandol Span
.target Rhag Garmason
    .accept 634 >> Accept Plea To The Alliance
step
    .goto 1417,45.9,47.5
.target Captain Nials
>>Talk to |cRXP_FRIENDLY_Captain Nials|r
    .turnin 634 >> Turn in Plea To The Alliance
step
    #xprate >1.3
    .goto 1417,46.6,47.0
.target Skuerto
>>Talk to |cRXP_FRIENDLY_Skuerto|r
    .turnin 690 >> Turn in Malin's Request
    .isOnQuest 690
step
    .goto 1417,45.8,46.1
    .fp Arathi >> Get the Arathi Highlands flight path
step
.isOnQuest 647
>>Run to Southshore and go downstairs in the inn. Turn in before the timer is up. Watch out for the courier on the road.
	.unitscan Forsaken Bodyguard
.goto 1424,52.2,58.6
.target Brewmeister Bilger
>>Talk to |cRXP_FRIENDLY_Brewmeister Bilger|r
    .turnin 647 >> Turn in MacKreel's Moonshine
step
    .goto 1424,51.0,66.6
    .accept 98459 >> Accept A Lack of Virtue
    >>Talk to |cRXP_FRIENDLY_Tom "Half-fish"|r in Southshore
step
	.goto 1424,50.5,57.2
.target Loremaster Dibbs
>>Talk to |cRXP_FRIENDLY_Loremaster Dibbs|r
    .turnin 538 >> Turn in Southshore
	.isOnQuest 538
step
    .xp <30,1
    .goto 1424,51.4,58.5
.target Lieutenant Farren Orinelle
>>Talk to |cRXP_FRIENDLY_Lieutenant Farren Orinelle|r
    .accept 536 >> Accept Down the Coast
step
    .xp <30,1
    .goto 1424,44.0,67.6
	>> Kill murlocs in the area
    .complete 536,1 --Kill Torn Fin Tidehunter (x10)
    .complete 536,2 --Kill Torn Fin Oracle (x10)
step
    .xp <30,1
    .goto 1424,51.4,58.5
>>Talk to |cRXP_FRIENDLY_Lieutenant Farren Orinelle|r
    .turnin 536 >> Turn in Down the Coast
.target Lieutenant Farren Orinelle
    .accept 559 >> Accept Farren's Proof
step
    .xp <30,1
    .goto 1424,42.3,68.3
	>> Kill murlocs and loot them for their head
    .complete 559,1 --Collect Murloc Head (x10)
step
    .xp <30,1
    .goto 1424,51.4,58.5
>>Talk to |cRXP_FRIENDLY_Lieutenant Farren Orinelle|r
    .turnin 559 >> Turn in Farren's Proof
.target Lieutenant Farren Orinelle
    .accept 560 >> Accept Farren's Proof
step
    .xp <30,1
    .goto 1424,49.5,58.8
>>Talk to |cRXP_FRIENDLY_Marshal Redpath|r
    .turnin 560 >> Turn in Farren's Proof
.target Marshal Redpath
    .accept 561 >> Accept Farren's Proof
step
    .xp <30,1
    .goto 1424,51.4,58.4
>>Talk to |cRXP_FRIENDLY_Lieutenant Farren Orinelle|r
    .turnin 561 >> Turn in Farren's Proof
.target Lieutenant Farren Orinelle
    .accept 562 >> Accept Stormwind Ho!
step
    .xp <30,1
    .goto 1424,57.1,67.4
	>> Kill naga in the area, you may need to go in the water if you get unlucky spawns
    .complete 562,1 --Kill Daggerspine Shorehunter (x10)
    .complete 562,2 --Kill Daggerspine Siren (x10)
step
    .xp <30,1
    .goto 1424,51.4,58.5
>>Talk to |cRXP_FRIENDLY_Lieutenant Farren Orinelle|r
    .turnin 562 >> Turn in Stormwind Ho!
.target Lieutenant Farren Orinelle
    .accept 563 >> Accept Reassignment
step
    .goto 1424,49.3,52.3
    .fp Southshore >> Get the Southshore flight path
step
    #role A,B,C
    .zone Tirisfal Glades >> Ruins of Lordaeron with your group: from Southshore follow the road north past Hillsbrad Fields and round Dalaran, then swim north up Lordamere Lake into Tirisfal Glades. Horde land: keep off the roads
step
    #role A,B,C
    .goto 1420,61.9,70.5
    >>Enter the Ruins of Lordaeron: the ruined city above the Undercity, on the east side of the courtyard on the way to the elevators, up the stairs behind an iron portcullis
step
    #role A,B,C
    .accept 95250 >> Accept Abominable Creatures
    .target Captain Truman
    >>|cRXP_FRIENDLY_Captain Truman|r is on your left as you zone in
step
    #role A,B,C
    >>Clear the Ruins (the bosses in any order). Kill |cRXP_ENEMY_The Baron|r for his head. Loot what starts the other three (click each in your bags): the first |cRXP_LOOT_Bloodied Insignia|r from the undead, then nine more; the |cRXP_LOOT_Crest of Lordaeron|r (top of the tower by the spider courtyard or by The Abandoned, behind the banshee's door in the spider courtyard, or the floor of the stair room across from Bjork's courtyard); the |cRXP_LOOT_Blood-Stained Letter|r by Edward Heartweaver's body near |cRXP_ENEMY_Rath'mael|r
    .complete 95250,1
    .accept 95195 >> Accept Bloodied Insignia
    .complete 95195,1
    .accept 95189 >> Accept Crest of Lordaeron
    .accept 92415 >> Accept Remember That I Love You
step
    #role A,B,C
    .turnin 95250 >> Turn in Abominable Creatures
    .target Captain Truman
    .isQuestComplete 95250
step
    #role A,B,C
    .zone Western Plaguelands >> Leave the Ruins and head east into the Western Plaguelands, then south to Chillwind Camp
    .isOnQuest 95189
step
    .goto 1422,42.9,85.0
    >>Head north farming turtle meat along the river, once you get at the end of the river, head northwest into WPL. You don't need all 10 meat yet.
    .fp Chillwind >> Get the Chillwind Camp flight path
step
    .goto 1422,42.9,85.0,-1
    .goto 1424,49.3,52.3,-1
    .fly Wetlands>> Fly to Wetlands
step
    .goto 1437,10.6,60.5
>>Talk to |cRXP_FRIENDLY_Glorin Steelbrow|r
    .turnin 292 >> Turn in The Eye of Paleth
.target Glorin Steelbrow
    .accept 293 >> Accept Cleansing the Eye
step
    .goto 1437,7.8,57.4
    .turnin 98459 >> Turn in A Lack of Virtue
    .target Bart Tidewater
    .isOnQuest 98459
step
    .goto 1437,12.1,64.1
    .turnin 321 >> Turn in Lightforge Iron
    .accept 324 >> Accept The Lost Ingots
step
    .goto 1437,10.1,69.5
	>> Kill murlocs and loot them for ingots. The droprate can be very low.
    .complete 324,1 --Collect Lightforge Ingot (x5)
step
    .goto 1437,10.6,60.4
>>Talk to |cRXP_FRIENDLY_Glorin Steelbrow|r
    .turnin 324 >> Turn in The Lost Ingots
.target Glorin Steelbrow
    .accept 322 >> Accept Blessed Arm
step
    .goto 1437,9.9,57.4
.target Captain Stoutfist
>>Talk to |cRXP_FRIENDLY_Captain Stoutfist|r
    .turnin 474 >> Turn in Defeat Nek'rosh
step << !Mage
	.goto 1437,9.3,59.4
    .fly Ironforge>> Fly to Ironforge
step << Mage
    .zone Ironforge >> Teleport to Ironforge
step
    .goto 1455,63.8,67.8
>>Talk to |cRXP_FRIENDLY_Sara Balloo|r
    .turnin 637 >> Turn in Sully Balloo's Letter
.target Sara Balloo
    .accept 683 >> Accept Sara Balloo's Plea
step
    .goto 1455,39.3,55.9
>>Talk to |cRXP_FRIENDLY_King Magni Bronzebeard|r
    .turnin 683 >> Turn in Sara Balloo's Plea
.target King Magni Bronzebeard
    .accept 686 >> Accept A King's Tribute
step
    .goto 1455,38.7,87.2
>>Talk to |cRXP_FRIENDLY_Grand Mason Marblesten|r
    .turnin 686 >> Turn in A King's Tribute
.target Grand Mason Marblesten
    .accept 689 >> Accept A King's Tribute

step
    #role A,B,C
    .zone Stormwind City >> Take the Deeprun Tram to Stormwind: the Ruins of Lordaeron hand-ins
    .isOnQuest 95189
step
    #role A,B,C
    .goto 1453,68.4,29.1
    .turnin 95189 >> Turn in Crest of Lordaeron
    .target Lady Dena Kennedy
    >>In Stormwind Keep's Royal Gallery
    .isOnQuest 95189
step
    #role A,B,C
    .goto 1453,56.3,54.0
    .turnin 92415 >> Turn in Remember That I Love You
    .target Orphan Matron Nightingale
    >>In front of the Cathedral of Light
    .isOnQuest 92415
step
    #role A,B,C
    .goto 1453,69.2,82.7
    .turnin 95195 >> Turn in Bloodied Insignia
    .target General Marcus Jonathan
    >>By the city gate
    .isQuestComplete 95195]])
